// PorNo! Android
// porNo.java
// @author Vivek Bhookya

package us.mrvivacio.porno;

import android.content.Intent;
import android.net.Uri;
import android.provider.Browser;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

public class porNo {
    private static String TAG = "dawg";

    // read me https://stackoverflow.com/questions/4833480/have-i-reached-the-limits-of-the-size-of-objects-javascript-in-my-browser-can-ha


    /*
     * Function isPorn
     * UNREFINED !! put me in another dedicated class of my own pleaseeeee
     * Checks only if the url contains any mention of a porn url
     * Ya boi Vivek out here writing a porn filter part 2!!!!!!!!!
     * @param url The url whose domain name we check against the porn sites
     */
    public static boolean isPorn(String url) {
        // Strip mobile. or m.
        int stop = url.length();
        url = url.trim().toLowerCase();

        if (url.length() < 1) {
            return false;
        }

        if (url.contains(" ")) {
            return false;
        }

        if (!url.contains(".")) {
            return false;
        }



        // Avoid fightthenewdrug and github
        if (!url.contains("fightthenewdrug") && !url.contains("github")) {
//            Log.d(TAG, "isPorn: URL = " + url);

            // O(n) worst case feels bad but whO(l)esome porn-checker feels good
            for (int i = 0; i < pornLinks.length; i++) {
                if (url.contains(pornLinks[i])) {
                    // GET THE FUCK OUTTTTTTTTTTTTTTT
//                    Log.d(TAG, "isPorn: TRUE");

                    return true;
                }
            }
        }

        // Inconclusive
        return false;
    }

    public static boolean isPornDomain(String url) {
        // Strip mobile. or m.
        int stop = url.length();
        url = url.trim().toLowerCase();

        // 4 because p.co (example) could be a real porn site and don't wanna skip those
        if (url.length() < 4) {
            return false;
        }


        // Return false for these URLs to avoid disrupting browsing experience
        // ie trying to look at porNo.js on my Github shouldn't trigger lmao
        if (    url.contains("fightthenewdrug") ||
                url.contains("github") ||
                url.contains("chrome")   ) {
            return false;
        }

        // Avoid fightthenewdrug and github
        else {
            Log.d(TAG, "isPorn: URL = " + url);

            // O(n) worst case feels bad but whO(l)esome porn-checker feels good
            for (int i = 0; i < pornDomains.length; i++) {
                if (url.contains(pornDomains[i])) {
                    // GET THE FUCK OUTTTTTTTTTTTTTTT
//                    Log.d(TAG, "isPorn: TRUE");

                    return true;
                }
            }
        }

        // Inconclusive
        return false;
    }

    private static String [] pornDomains = {
            ".xxx",".adult",".porn","anissa-kate","anissakate","manyvids",
            ".sex","jizzman","tube8","barelist", "hugesex", "hugesex/en/","xnxx",
            "pornhub","youporn","thefappening","lezbiyenporno",
            "godfatherporn","hotgirlclub","perfectgirls","mikeinbrazil",
            "nitroflare-porn","pornfack","porngals4","pornve","pornzog",
            "sexuria.to","straight.fleshbot",
            "ulsexvideo", "mobile.bangbros","uviporn","vporn","xpornplease","xxhdporn",
            "adultfreex","dirtypornvids","devporn","forbiddenplaygroundxxx",
            "devporn","123porn.me","devporn","fapvibe","redwap.me","xhamster.news",
            "excitemii", "tubsexer","fapality","vip-pornfilms","adultbliss","3d-porn.us",
            "naughtyamericavr","1sexporn","juggsjoy",
            "m.fxporn","pornfactor","pornoxo","teamskeet","ultrahdporn.eu","vepornhd.club",
            "vixvids.to","xporn.es","anybunny.mobi",
            "barscapital.ru","bb-magazine.ru","fullhdpornmovie","hdpornstarz","hotnudephoto",
            "jizzboom","nesaporn.mobi","nudedesigirls",
            "pornpics","pornsexerotica","porntubeclub","rajwap.xyz","redhdtube.xxx","redhub",
            "sexpussynude","smutindia", "forbiddenplaygroundxxx",
            "teenpornvideo.xxx","upornia","weliketosuck.us","xxx-picture","xxxymovies",
            "3movs","4tube",
            "pornhd","rushporn","spankbang","thumbzilla","porno-hub","hd-porn",
            "redtube","xtapes.to",
            ".porno","vid27", "porno.", "xnxx", "hugesex", ".sexy","swallowed", "newsexxxx","puba",
            "evanotty","xfreehd", ".webcam",".exposed", "pornhub", "foxporn","realgfporn","34jpornstar.us","sex3","sexu",
            "titsbox","tryboobs","tubedupe","tubeon.mobi","porn4days", "tubepornclassic","pornav","tubous","nevid.us","viptube",
            "vivatube","vivud","voyeurhit","vporn","wetplace",
            "winporn","xcafe","funnyjunk/nsfw","xozilla","xxxdan", "yeptube","yourlust","ah-me","analdin",
            "dirtypornivds","zemporn","stocking-tease", "pornvideohunter","zmovs","fuck55","3gpkings","kompoz.me",
            "realitykings","pornolaba","foxporns","anyporn", "videosexarchive","redwap.me","avelip","anysex","megacam.me",
            "longsextubes","bustymomsvideo","clipeu","brazzers", "bangbus","assparade","tuboff","erome",
            "monstersofcock","porno-wonder","siska","gofucker", "pornalized","pornoid","pornoxo","pornpy",
            "pornsharing","pornwatchers","pornxs","bigmouthfuls", "bigtitsroundasses","chaturbate","tugjobs","flyingjizz",
            "jizzbunker","fap18","euphoriaporn","japan-whores", "pinkrod","uploporn","hdzog","iceporn","hotmovs",
            "hellporno","bigtitcreampie","camvideos","txxx",
            "eskimotube","beeg","milfsoup","flyflv", "brownbunnies","mrporngeek.porn","upornia","bangbrostubehd",
            "adultdvdempire","bangbrosclips","faapy","porndish",
            "magicalfeet","topchats","adultreviews","18tokyo",
            "1virgins","1girl1camera","pridestudios","1by-day",
            "1800dialadick","1passforallsites","freeones",
            "dreammovies","pornhubfillesalope","girlygifporn",
            "arabicdancevideo.blogspot","kellydivine","tubepornstars",
            "tubepornstars","vintagehairy","lookatvintage","pornorama",
            "ass4all","cindymovies", "onlygirlvideos", "rofipot",
            "spankwire", "arabesexy", "megamovie.us", "nakedboobs",
            "teencamvids", "nudeboobshotpics", "sugarbbw",
            "sexbotbonnasse", "salope.1japonsex", "nudematurewomenphotos",
            "eroticbeauties", "milfs30", "freshmatureporn", "matureshine",
            "wetmaturewhores", "mature-galleries", "owsmut", "webcam",
            "maturelle", "toppornsites", "womenmaturepics",
            "all-free-nudes-old-granny-mature-women-xxx", "maturepornhub",
            "nudeold", "uniquesexymoms", "nude.oldies", "riomature",
            "hot-naked-milfs", "stifiersmoms", "multimature",
            "oldhotmoms", "matureoracle", "hungrymatures", "milfous",
            "watersweb", "eromatures", "mom50", "maturesinstockings",
            "imaturewomen", "wetmaturewomen", "matureandyoung",
            "momshere", "riomoms", "kissmaturesgo", "bitefalm",
            "milfionaire", "sexymaturethumbs", "maturosexy", "6mature9",
            "hotnakedoldies", "reddit.com/r/NSFW411", "reddit.com/r/nsfw",
            "reddit.com/r/suicidegirls", "reddit.com/r/nsfw2",
            "reddit.com/r/TipOfMyPenis", "reddit.com/r/bonermaterial",
            "reddit.com/r/porn", "reddit.com/r/nsfw411", "reddit.com/r/iWantToFuckHer",
            "reddit.com/r/exxxtras", "reddit.com/r/distension",
            "reddit.com/r/bimbofetish", "reddit.com/r/christiangirls",
            "reddit.com/r/cuckold", "reddit.com/r/dirtygaming",
            "reddit.com/r/sexybutnotporn", "reddit.com/r/femalepov",
            "reddit.com/r/omgbeckylookathiscock", "reddit.com/r/milf",
            "reddit.com/r/gonewild30plus", "reddit.com/r/ohnomomwentwild",
            "reddit.com/r/preggoporn", "reddit.com/r/legalteens",
            "reddit.com/r/collegesluts", "reddit.com/r/adorableporn",
            "reddit.com/r/legalteensXXX", "reddit.com/r/gonewild18", "reddit.com/r/18_19",
            "reddit.com/r/just18", "reddit.com/r/realgirls", "reddit.com/r/amateur",
            "reddit.com/r/homemadexxx", "reddit.com/r/AmateurArchives",
            "reddit.com/r/dirtypenpals", "reddit.com/r/FestivalSluts",
            "reddit.com/r/CollegeAmateurs", "reddit.com/r/amateurcumsluts",
            "reddit.com/r/nsfw_amateurs", "reddit.com/r/funwithfriends",
            "reddit.com/r/randomsexiness", "reddit.com/r/amateurporn",
            "reddit.com/r/normalnudes", "reddit.com/r/Camwhores", "reddit.com/r/camsluts",
            "reddit.com/r/SluttyStrangers", "reddit.com/r/GoneWild",
            "reddit.com/r/PetiteGoneWild", "reddit.com/r/gonewildstories",
            "reddit.com/r/GoneWildTube", "reddit.com/r/treesgonewild",
            "reddit.com/r/gonewildaudio", "reddit.com/r/GWNerdy", "reddit.com/r/gonemild",
            "reddit.com/r/altgonewild", "reddit.com/r/gifsgonewild",
            "reddit.com/r/analgw", "reddit.com/r/gonewildsmiles",
            "reddit.com/r/onstageGW", "reddit.com/r/RepressedGoneWild",
            "reddit.com/r/bdsmgw", "reddit.com/r/UnderwearGW", "reddit.com/r/LabiaGW",
            "reddit.com/r/TributeMe", "reddit.com/r/WeddingsGoneWild",
            "reddit.com/r/gwpublic", "reddit.com/r/assholegonewild",
            "reddit.com/r/leggingsgonewild", "reddit.com/r/dykesgonewild",
            "reddit.com/r/gonewild30plus", "reddit.com/r/gonewild18",
            "reddit.com/r/ohnomomwentwild", "reddit.com/r/GWCouples",
            "reddit.com/r/gonewildcouples", "reddit.com/r/gwcumsluts",
            "reddit.com/r/WouldYouFuckMyWife", "reddit.com/r/gonewildcurvy",
            "reddit.com/r/GoneWildplus", "reddit.com/r/BigBoobsGW",
            "reddit.com/r/bigboobsgonewild", "reddit.com/r/AsiansGoneWild",
            "reddit.com/r/gonewildcolor", "reddit.com/r/indiansgonewild",
            "reddit.com/r/workgonewild", "reddit.com/r/GoneWildScrubs",
            "reddit.com/r/NSFW_Snapchat", "reddit.com/r/snapchat_sluts",
            "reddit.com/r/snapleaks", "reddit.com/r/wifesharing", "reddit.com/r/hotwife",
            "reddit.com/r/rule34", "reddit.com/r/hentai", "reddit.com/r/ecchi",
            "reddit.com/r/futanari", "reddit.com/r/hentai_gif", "reddit.com/r/doujinshi",
            "reddit.com/r/overwatch_porn", "reddit.com/r/rule34_comics",
            "reddit.com/r/sex_comics", "reddit.com/r/BDSM", "reddit.com/r/Bondage",
            "reddit.com/r/BDSMcommunity", "reddit.com/r/bdsmgw", "reddit.com/r/blowjobs",
            "reddit.com/r/lipsthatgrip", "reddit.com/r/deepthroat",
            "reddit.com/r/onherknees", "reddit.com/r/blowjobsandwich", "reddit.com/r/ass",
            "reddit.com/r/asstastic", "reddit.com/r/facedownassup",
            "reddit.com/r/assinthong", "reddit.com/r/bigasses", "reddit.com/r/buttplug",
            "reddit.com/r/TheUnderbun", "reddit.com/r/booty", "reddit.com/r/anal",
            "reddit.com/r/analgw", "reddit.com/r/painal", "reddit.com/r/masterofanal",
            "reddit.com/r/buttsharpies", "reddit.com/r/asshole",
            "reddit.com/r/AssholeBehindThong", "reddit.com/r/assholegonewild",
            "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
            "reddit.com/r/boobies", "reddit.com/r/tinytits", "reddit.com/r/TittyDrop",
            "reddit.com/r/burstingout", "reddit.com/r/boltedontits",
            "reddit.com/r/boobbounce", "reddit.com/r/boobs", "reddit.com/r/downblouse",
            "reddit.com/r/homegrowntits", "reddit.com/r/cleavage",
            "reddit.com/r/breastenvy", "reddit.com/r/youtubetitties",
            "reddit.com/r/torpedotits", "reddit.com/r/thehangingboobs",
            "reddit.com/r/BustyPetite", "reddit.com/r/hugeboobs", "reddit.com/r/stacked",
            "reddit.com/r/BigBoobsGW", "reddit.com/r/bigboobsgonewild",
            "reddit.com/r/pokies", "reddit.com/r/ghostnipples", "reddit.com/r/nipples",
            "reddit.com/r/GirlswithNeonHair", "reddit.com/r/shorthairchicks",
            "reddit.com/r/blonde", "reddit.com/r/datgap", "reddit.com/r/girlsinyogapants",
            "reddit.com/r/stockings", "reddit.com/r/legs", "reddit.com/r/thighhighs",
            "reddit.com/r/tightshorts", "reddit.com/r/pussy", "reddit.com/r/rearpussy",
            "reddit.com/r/innie", "reddit.com/r/simps", "reddit.com/r/pelfie",
            "reddit.com/r/LabiaGW", "reddit.com/r/moundofvenus",
            "reddit.com/r/Hotchickswithtattoos", "reddit.com/r/sexyfrex",
            "reddit.com/r/tanlines", "reddit.com/r/oilporn", "reddit.com/r/SexyTummies",
            "reddit.com/r/theratio", "reddit.com/r/fitgirls",
            "reddit.com/r/bodyperfection", "reddit.com/r/gonewildcurvy",
            "reddit.com/r/curvy", "reddit.com/r/gonewildplus", "reddit.com/r/thick",
            "reddit.com/r/juicyasians", "reddit.com/r/voluptuous",
            "reddit.com/r/biggerthanyouthought", "reddit.com/r/jigglefuck",
            "reddit.com/r/chubby", "reddit.com/r/BustyPetite", "reddit.com/r/dirtysmall",
            "reddit.com/r/petitegonewild", "reddit.com/r/xsmallgirls",
            "reddit.com/r/funsized", "reddit.com/r/hugedicktinychick",
            "reddit.com/r/volleyballgirls", "reddit.com/r/Ohlympics",
            "reddit.com/r/celebnsfw", "reddit.com/r/WatchItForThePlot",
            "reddit.com/r/nsfwcelebarchive", "reddit.com/r/celebritypussy",
            "reddit.com/r/oldschoolcoolNSFW", "reddit.com/r/cumsluts",
            "reddit.com/r/GirlsFinishingTheJob", "reddit.com/r/cumfetish",
            "reddit.com/r/amateurcumsluts", "reddit.com/r/cumcoveredfucking",
            "reddit.com/r/cumhaters", "reddit.com/r/thickloads",
            "reddit.com/r/before_after_cumsluts", "reddit.com/r/creampies",
            "reddit.com/r/throatpies", "reddit.com/r/FacialFun",
            "reddit.com/r/cumonclothes", "reddit.com/r/HappyEmbarrassedGirls",
            "reddit.com/r/unashamed", "reddit.com/r/borednignored",
            "reddit.com/r/latinas", "reddit.com/r/AsianHotties",
            "reddit.com/r/AsiansGoneWild", "reddit.com/r/realasians",
            "reddit.com/r/juicyasians", "reddit.com/r/AsianNSFW",
            "reddit.com/r/nextdoorasians", "reddit.com/r/asianporn",
            "reddit.com/r/bustyasians", "reddit.com/r/IndianBabes",
            "reddit.com/r/indiansgonewild", "reddit.com/r/NSFW_Japan",
            "reddit.com/r/javdownloadcenter", "reddit.com/r/kpopfap",
            "reddit.com/r/NSFW_Korea", "reddit.com/r/WomenOfColor",
            "reddit.com/r/darkangels", "reddit.com/r/blackchickswhitedicks",
            "reddit.com/r/ebony", "reddit.com/r/ginger", "reddit.com/r/redheads",
            "reddit.com/r/palegirls", "reddit.com/r/pawg", "reddit.com/r/NSFW_GIF",
            "reddit.com/r/nsfw_gifs", "reddit.com/r/porn_gifs",
            "reddit.com/r/porninfifteenseconds", "reddit.com/r/CuteModeSlutMode",
            "reddit.com/r/60fpsporn", "reddit.com/r/NSFW_HTML5", "reddit.com/r/twingirls",
            "reddit.com/r/groupofnudegirls", "reddit.com/r/nsfwhardcore",
            "reddit.com/r/SheLikesItRough", "reddit.com/r/strugglefucking",
            "reddit.com/r/hugedicktinychick", "reddit.com/r/jigglefuck",
            "reddit.com/r/freeuse", "reddit.com/r/whenitgoesin",
            "reddit.com/r/outercourse", "reddit.com/r/gangbang", "reddit.com/r/breeding",
            "reddit.com/r/pegging", "reddit.com/r/insertions", "reddit.com/r/passionx",
            "reddit.com/r/facesitting", "reddit.com/r/nsfw_plowcam",
            "reddit.com/r/pronebone", "reddit.com/r/fuxtaposition",
            "reddit.com/r/60fpsporn", "reddit.com/r/highresNSFW",
            "reddit.com/r/NSFW_HTML5", "reddit.com/r/incestporn", "reddit.com/r/wincest",
            "reddit.com/r/sarah_xxx", "reddit.com/r/remylacroix",
            "reddit.com/r/Anjelica_Ebbi", "reddit.com/r/lesbians",
            "reddit.com/r/StraightGirlsPlaying", "reddit.com/r/girlskissing",
            "reddit.com/r/mmgirls", "reddit.com/r/dykesgonewild",
            "reddit.com/r/holdthemoan", "reddit.com/r/O_faces", "reddit.com/r/jilling",
            "reddit.com/r/gettingherselfoff", "reddit.com/r/quiver",
            "reddit.com/r/suctiondildos", "reddit.com/r/GirlsHumpingThings",
            "reddit.com/r/forcedorgasms", "reddit.com/r/mmgirls",
            "reddit.com/r/ruinedorgasms", "reddit.com/r/grool", "reddit.com/r/squirting",
            "reddit.com/r/ladybonersgw", "reddit.com/r/massivecock",
            "reddit.com/r/chickflixxx", "reddit.com/r/gaybrosgonewild",
            "reddit.com/r/OnOff", "reddit.com/r/nsfwoutfits",
            "reddit.com/r/Bottomless_Vixens", "reddit.com/r/girlswithglasses",
            "reddit.com/r/lingerie", "reddit.com/r/candidfashionpolice",
            "reddit.com/r/bikinis", "reddit.com/r/collared", "reddit.com/r/tightshorts",
            "reddit.com/r/seethru", "reddit.com/r/sweatermeat", "reddit.com/r/cfnm",
            "reddit.com/r/nsfwcosplay", "reddit.com/r/nsfwcostumes",
            "reddit.com/r/girlsinschooluniforms", "reddit.com/r/WtSSTaDaMiT",
            "reddit.com/r/tightdresses", "reddit.com/r/upskirt", "reddit.com/r/stockings",
            "reddit.com/r/thighhighs", "reddit.com/r/leggingsgonewild",
            "reddit.com/r/assinthong", "reddit.com/r/AssholeBehindThong",
            "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
            "reddit.com/r/ChangingRooms", "reddit.com/r/workgonewild",
            "reddit.com/r/trashyboners", "reddit.com/r/FlashingGirls",
            "reddit.com/r/publicflashing", "reddit.com/r/sexinfrontofothers",
            "reddit.com/r/NotSafeForNature", "reddit.com/r/gwpublic",
            "reddit.com/r/realpublicnudity", "reddit.com/r/socialmediasluts",
            "reddit.com/r/Tgirls", "reddit.com/r/traps", "reddit.com/r/futanari",
            "reddit.com/r/pornvids", "reddit.com/r/nsfw_videos",
            "reddit.com/r/dirtysnapchat", "reddit.com/r/randomactsofblowjob",
            "reddit.com/r/NSFWFunny", "reddit.com/r/confusedboners",
            "reddit.com/r/dirtykikpals", "reddit.com/r/nsfw_wtf",
            "reddit.com/r/randomactsofmuffdive", "reddit.com/r/gore",
            "reddit.com/r/watchpeopledie", "reddit.com/r/popping", "golden-moms",
            "madmamas", "womanolder", "matureland", "motherstits",
            "unshavenpussies", "pornmaturepics", "105matures",
            "momstaboo", "broslingerie", "elderly-women", "upskirttop",
            "bushypussies", "amateurmaturewives", "universeold",
            "unshavengirls", "oldernastybitches", "maturewant",
            "juliepost", "mulligansmilfs", "bestmaturewomen", "riomature",
            "mature-orgasm", "inlovewithboobs", "riotits",
            "nakedbustytits", "ass-butt", "matureladiespics",
            "pornmaturewomen", "nudemomphotos", "secinsurance",
            "bigfreemature", "mature-women-tube", "hotnudematures",
            "oldsexybabes", "matureasspics", "mature30plus",
            "matureamour", "the momsfucking", "boobymilf",
            "fantasticwomans", "xxxmatureposts", "alloldpics",
            "lenawethold", "mature.nl", "wifezilla", "chubbygalls",
            "nudematurepics", "matureal", "thexmilf", "cocomilfs",
            "zmilfs", "wild-matures", "horny-matures", "grandmabesttube",
            "grandmabesttube", "bestmilftube", "needmilf", "girlmature",
            "bestmatureclips", "lustfuloldies", "riomoms", "maturehotsex",
            "bettermilfs", "milfionaire", "oldercherry", "oldercherry",
            "sexymilfpussy", "maturepornpics", "action36", "dianapost",
            "babesclub", "lovely-mature", "bestmaturesthumb",
            "myfreemoms", "milfatwork", "milfgals", "olderwomenarchive",
            "milfmomspics", "pornvideoitaly", "stiflersmilfs",
            "maturenags", "maturenakedsluts", "tgpmaturewoman",
            "idealwifes", "maturewitch", "hqmaturemovs",
            "mature-women-tube", "olderwomentaboo", "chocomilf",
            "milfparanoia", "momsnightjob", "matureintros", "booloo",
            "bigbuttmature", "maturetube", "mature30-45", "pornbox",
            "honestpornreviews", "crocreview", "realitypornsearch",
            "paypornlist", "rogreviews", "thetongue", "porninspector",
            "backroomfacials", "pawg", "nailedhard", "fuckteamfive",
            "bangbros18teens", "partyofthree", "latinarampage",
            "backroommilf", "canhescore", "mujeresculonas", "xkeezmovies",
            "bangpov", "bang", "porndoe", "blowjobninjas", "mrpornx",
            "mydirtymaid", "stepmomvideos", "rabbitsreviews", "empflix",
            "boobpedia", "dorminvasion", "easyporn", "rexmag", "fux",
            "pornadept", "mylifeinbrazil", "yespornpleae", "ultrahorny",
            "momishorny", "bangoncasting", "bangbros-free", "720porn",
            "funvidporn", "bangpass", "siterip4fun", "bangbros",
            "porntube", "youjizz", "redtube", "xvideos", "xhamster",
            "xnxx", "hclips", "porn", "tnaflix",
            "tube8", "hd21", "newhd.xxx", "spankbang", "drtuber",
            "spankwire", "keezmovies", "nuvid", "sunporno",
            "bravotube", "bravoteens", "drtuber", "mylust",
            "overthumbs", "palmtube", "pornhd", "porn300", "sexvid.xxx",
            "xxxbunker", "mofosex", "xbabe", "updatetube", "befuck",
            "bravoerotica", "masseurporn", "hdmovz", "pornrox",
            "pornmaki", "pornid.xxx", "inxporn", "slutload", "proporn",
            "fakeporn", "pornhost", "handjobhub", "vpornvideos",
            "myxvids", "dansmovies", "fapdu", "rude",
            "topfreepornvideos", "freudbox", "pornheed", "hdporn",
            "orgasm", "pornrabbit", "madthumbs", "fux", "eroxia",
            "deviantclip", "xxvids", "h2porn", "apetube", "metaporn",
            "elephanttube", "long.xxx", "pornerbros", "iporntv", "pron",
            "pornplanner", "mypornbible", "badjojo", "findtubes",
            "lasmejoreswebsporno/en", "pornmd", "nudevista",
            "it.bing/videos/search?q=por",
            "video.search.yahoo/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=ZaF57phvPYQ,138531013",
            "video.search.yahoo/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=t2freeITUJs,1526679329&fr2=p%3As%2Cv%3Av&save=0",
            "adultvideofinder", "awejmp", "imlive", "evilangellive",
            "awejmp", "joyourself", "xlovecam", "cams", "pornication",
            "delhisexchat", "sexier", "secure.vividcams", "privatefeeds",
            "streamate", "slutroulette", "t.hrtya", "watchmyexgf",
            "watchmygf.cc", "fantasti.cc", "watchmygf.me", "iknowthatgirl",
            "daredorm", "crazycollegegfs", "analized", "punishtube",
            "stufferdb", "88gals", "sexforums/gallery", "apina.biz",
            "babe-lounge", "fuskator", "gotporn", "arabianchicks",
            "extremetube", "fetishpapa", "fuckler", "fantasti.cc",
            "bdsmstreak", "zzcartoon", "animeidhentai", "hentaihaven",
            "simply-hentai", "hentaigasm", "fakku", "gelbooru",
            "hentaipulse", "porcore", "hentaischool",
            "chan.sankakucomplex", "hentai-foundry", "babesrater",
            "punchpin", "lustpin", "sexlikereal", "vrsmash", "stasyq",
            "mobilevrxxx", "realitylovers", "myporngay", "zzgays",
            "gay-lounge", "justusboys", "iptorrents/torrents", "rarbg",
            "pussytorrents", "porn", "yourdailypornstars",
            "bestpornstardb", "babepedia", "kindgirls", "playindiansex",
            "playindianporn", "viewdesisex", "hotsouthindiansex",
            "watchindianporn", "xpaja", "lesbian8", "kirtu",
            "velamma", "nutaku", "69games.xxx", "gamcore",
            "assist.lifeselector", "playforceone", "brazzersnetwork",
            "wct.link", "rk", "digitalplayground", "mofosnetwork",
            "gfrevenge", "twistysnetwork", "teamskeet", "bangbrosnetwork",
            "iyalc", "ddfnetwork", "braincash", "iyalc", "videosz",
            "hustler", "premiumbukkake", "javhd", "pornprosnetwork",
            "perfectgonzo", "alljapanesepass", "momsbangteens",
            "wickedpictures", "puffynetwork", "18videoz", "nubiles",
            "kinkyfamily", "allofgfs", "filf", "dorcelclub",
            "best-paypornsites", "nakednews", "playboy", "forumophilia",
            "jdforum", "freeones", "peachyforum", "sexyrealsexdolls",
            "spklmis", "toppornsites", "Tubegalore", "gaymaletube",
            "iXXX", "1piecehentai", "2hentai", "2th", "4chan",
            "69ani", "8muses", "aerisdies", "allhentai",
            "animefootfetish", "animehentaimangas", "animetor",
            "animephile", "aryion", "asmhentai", "atsuifeet", "baidu",
            "baixarhentai", "bamtoki", "bangcartoons", "baramangaonline",
            "bbotoon", "bobx", "brasilhentai", "clickhentai",
            "codegeassxxx", "colorhentaimangas", "comicsfromhell",
            "comicsporno", "comicspornogratis", "comixhere",
            "deliciousdoujinshi", "dochentai", "doujin2", "doujin-th",
            "doujindaily", "doujinland", "doujinlife",
            "doujinloverandgiver", "doujinmode", "doujinpage",
            "doujinreader", "doujinroom", "doujins", "doujinshentai",
            "doujinshi rocks", "doujinshihentai", "doujinx", "e-hentai",
            "ecchitail", "ero-senin", "erolord", "eromanga-sokuhou",
            "eshentaionline", "exhentai", "fapdu", "ff10hentai",
            "ff12hentai", "ff7hentai", "finalxxxfantasy", "furaffinity",
            "futahentai", "futanarispash", "g6hentai", "gs-uploader",
            "gurrenhentai", "h-manga moe", "hakihome", "hbrowse",
            "hcomicbook", "hdarkzone", "hellven", "hentai-ddl",
            "hentai-free", "hentai-id", "hentai-ita", "hentai-manga",
            "hentaicafe", "hentaims", "hentaipink", "hentaltl",
            "hental2read", "hentai4me", "hentai4doujin", "hentai4manga",
            "hentai4u", "hentai666", "hentaibeast", "hentaiboxfr",
            "hentaibox", "hentaibunny", "hentaibusty", "hentaichan",
            "hentaicloud", "hentaicorner", "hentaifamed", "hentaifield",
            "hentaifox", "hentaifr", "hentaifromhell", "hentaigamech",
            "hentaigratuit", "hentaihere", "hentaihouse", "hentaihousext",
            "hentaihunt", "hentaiiXXX", "hentaijuggs", "hentailx",
            "hentailxers", "hentaimangabiz", "hentaimangaonline",
            "hentaimangaz", "hentainesia", "hentaiporns", "hentairead",
            "henairing", "hentairules", "hentaischool", "hentaisd",
            "hentaistack", "hentaivn", "hentype", "hgamecg", "hhhhhh",
            "high-hentai", "hime-doujins", "hipercool", "hitomi",
            "hmangasearcher", "hotdhentai", "ihentaimanga", "imagefap",
            "incesthentai", "junkuchan", "kimi-h", "komikhentai",
            "lolhentai", "lookmanga", "lovehentaimanga", "luscious",
            "ohentai", "mahenku", "manga12", "mangaboxes", "mangafap",
            "mangakawaiifeet", "manganude", "mangaray", "mangaseries",
            "mangawindow", "mapussy", "massivehentai", "maturemangas",
            "megahentaicomics", "milkyhentai", "minihentai",
            "muchodoujins", "muchohentai", "multporn", "mydoujins",
            "myhentaicomics", "myreadingmanga", "narutohentaigalleries",
            "nhentai", "nude-moon", "nxt-comics", "ohtori",
            "omorashi", "overwatchhentaidb", "palcomix", "pbxwwoec",
            "personahentai", "perveden", "pinayacenter", "plentyofhentai",
            "pomfpomf", "porncomics", "porncmix", "pornocomics",
            "pornsource", "pornxxxcomics", "primehentai", "proxer",
            "pururin", "r34comics", "readhentaidoujinshi",
            "readhentaimanga", "readincesthentai", "readmangahentai",
            "revistasequadrinhos", "ryuutama", "sextgem", "shentai",
            "simply-hentai", "sinnergate", "smdc-translations",
            "sohentai", "submanga", "sukahentai", "svscomics",
            "sweetyaoiparadise", "thedoujin", "thehentaiworld",
            "tmohentai", "truyen18", "tsumino", "underworld-scans",
            "fapworks", "vanillahentai", "ver-manga", "vercomicsporno",
            "vesquare", "watchhentaistream", "world-hentai", "xcartx",
            "xcomics4you", "xxcomics", "xxxyuna", "yaoichan",
            "yaoifox", "yaoihavenreborn", "yuri-ism", "yurimanga",
            "zizki", "zkomik", "findtubes", "1indiansex", "3rat",
            "4hen", "africansexvideos", "bananabunny", "cutepornvideos",
            "desimurga", "desisexclips", "dslady", "eroticperfection",
            "porn", "porn", "gaypormium", "gracefulnudes",
            "hot-dates", "hqlinks", "indiansex4u.xxx", "jav-porn",
            "legalporno", "luboeporno", "pinkythekinky", "sexsex.hu",
            "sexxxi", "semale.asia", "thefreecamsecret", "momsteachsex",
            "petardas", "89", "alohatube", "babosas", "callboyindia",
            "cam4", "cam4", "cam4.in", "youpornru", "cholotube", "cliphunter",
            "culosgratis", "cumlouder", "darering", "flirt4free",
            "fuq", "hairy", "labatidora", "leche69", "livejasmin",
            "locasporfollar", "lushstories", "mc-nudes", "myfreecams",
            "naughty", "penguinvids", "perfectgirls", "perucaseras",
            "pinkworld", "playvid", "puritanas", "rk",
            "roundandbrown", "truthordarepics", "videosdemadurasx",
            "x-ho", "xixx", "xtube", "xvideosnacional", "purebbwtube",
            "babes", "fotosmujeres.pibones", "rubber-kingdom",
            "savitabhabhi.mobi", "pinkvisualtgp", "antarvasna", "hot-gifz",
            "lechecaliente", "parejasfollando.es", "flirthookup", "cerdas",
            "chaturbate", "ledauphine", "freex.mobi", "gokabyle",
            "bdenjoymore.blogspot", "petardas", "conejox", "voyeurpipi",
            "gouines.pornoxxxi", "arabebaise", "ohasiatique", "poringa",
            "lisaannlovers11.tumblr", "h33t.to", "marocainenue",
            "gorgeousladies", "fille-nue-video", "teensnow",
            "theofficiallouisejenson", "yourather", "bootlust",
            "toonztube", "top-chatroulette", "videosfilleschaudes",
            "fillechaude", "femmesmuresx", "liberteenage", "coffeetube",
            "awesomeellalove.tumblr", "xnxxgifs", "saoulbadjojo",
            "beurettehot", "woodstockreborn.tumblr",
            "belles-femmes-arabes.blogspot", "xgouines", "couleurlvoirce",
            "3animalsextube", "moncloutube", "sexocean", "femdomempire",
            "babosas", "giude-asie", "beauxcul", "maghrebinnes.xl.cx",
            "xnxx-free", "xnxx.vc", "es.bravotube", "rubias19",
            "xxl.onxille", "asiataique-femme", "masalopeblack",
            "beautiful-nude-tens-exposed.tur", "pormhub", "cochonnevideosx", "videosanalesx",
            "dorceltv.xn.pl", "salope-marocaine", "jeunette18", "redtuve",
            "les-grosses", "yasminramos", "tukif", "adultwork",
            "hairy", "tendance-lesbienne", "indiansexstories", "eros",
            "7dog", "vivthomas", "teensnowxvideos",
            "x-art","chaturbate","pinkworld","pandamovies","muyzorras","uplust",
            "shemales","bigboobsalert","culx","falconstudios","nautilix","ovideox",
            "herbalviagraworld","primecurves","xbabe","webpnudes",
            "smutty","naughtyamerica","faketaxi","momjoi","dreammovies", "swallowed",
            "asspoint", "bobs-tube", "4tube", "canalporno", "eporner",
            "hdpornt", "kink", "milffox", "mypornstarbook", "xshare"
    };

    private static String [] pornLinks = {
        ".xxx",".adult",".porn","anissa-kate","anissakate","manyvids",
        ".sex","jizzman.com","tube8","barelist.com", "hugesex.tv", "hugesex.tv/en/","xnxx.com",
        "pornhub.com","youporn.com","thefappening.pro","lezbiyenporno.org",
        "godfatherporn.com","hotgirlclub.com","perfectgirls.net","mikeinbrazil.com",
        "nitroflare-porn.com","pornfack.com","porngals4.com","pornve.com","pornzog.com",
        "sexuria.to","straight.fleshbot.com",
        "ulsexvideo.com", "mobile.bangbros.com","uviporn.com","vporn.com","xpornplease.com","xxhdporn.com",
        "adultfreex.com","dirtypornvids.com","devporn.net","forbiddenplaygroundxxx.com",
        "devporn.net","123porn.me","devporn.net","fapvibe.com","redwap.me","xhamster.news",
        "excitemii.com", "tubsexer.com","fapality.com","vip-pornfilms.com","adultbliss.net","3d-porn.us",
        "naughtyamericavr.com","1sexporn.com","juggsjoy.com",
        "m.fxporn.net","pornfactor.net","pornoxo.com","teamskeet.com","ultrahdporn.eu","vepornhd.club",
        "vixvids.to","xporn.com.es","anybunny.mobi",
        "barscapital.ru","bb-magazine.ru","fullhdpornmovie.com","hdpornstarz.com","hotnudephoto.com",
        "jizzboom.com","nesaporn.mobi","nudedesigirls.net",
        "pornpics.com","pornsexerotica.com","porntubeclub.com","rajwap.xyz","redhdtube.xxx","redhub.co",
        "sexpussynude.com","smutindia.com", "forbiddenplaygroundxxx",
        "teenpornvideo.xxx","upornia.com","weliketosuck.us","xxx-picture.com","xxxymovies.com",
        "3movs.com","4tube.com",
        "pornhd.com","rushporn.com","spankbang.com","thumbzilla.com","porno-hub.com","hd-porn",
        "redtube.com","xtapes.to",
        ".porno","vid27.com", "porno.", "xnxx.com", "hugesex.tv", ".sexy","swallowed.com", "newsexxxx.com","puba.com",
        "evanotty.com","xfreehd.com", ".webcam",".exposed", "pornhub.com", "foxporn.com","realgfporn.com","34jpornstar.us","sex3.com","sexu.com",
        "titsbox.com","tryboobs.com","tubedupe.com","tubeon.mobi","porn4days", "tubepornclassic.com","pornav.net","tubous.com","nevid.us","viptube.com",
        "vivatube.com","vivud.com","voyeurhit.com","vporn.com","wetplace.com",
        "winporn.com","xcafe.com","funnyjunk.com/nsfw","xozilla.com","xxxdan.com", "yeptube.com","yourlust.com","ah-me.com","analdin.com",
        "dirtypornivds.com","zemporn.com","stocking-tease.com", "pornvideohunter.com","zmovs.com","fuck55.net","3gpkings.com","kompoz.me",
        "realitykings.com","pornolaba.com","foxporns.com","anyporn.com", "videosexarchive.com","redwap.me","avelip.com","anysex.com","megacam.me",
        "longsextubes.com","bustymomsvideo.com","clipeu.com","brazzers.com", "bangbus.com","assparade.com","tuboff.com","erome.com",
        "monstersofcock.com","porno-wonder.com","siska.tv","gofucker.com", "pornalized.com","pornoid.com","pornoxo.com","pornpy.com",
        "pornsharing.com","pornwatchers.com","pornxs.com","bigmouthfuls.com", "bigtitsroundasses.com","chaturbate.com","tugjobs.com","flyingjizz.com",
        "jizzbunker.com","fap18.net","euphoriaporn.com","japan-whores.com", "pinkrod.com","uploporn.com","hdzog.com","iceporn.com","hotmovs.com",
        "hellporno.com","bigtitcreampie.com","camvideos.com","txxx.com",
        "eskimotube.com","beeg.com","milfsoup.com","flyflv.com", "brownbunnies.com","mrporngeek.porn","upornia.com","bangbrostubehd.com",
        "adultdvdempire.com","bangbrosclips.com","faapy.com","porndish.com",
        "magicalfeet.com","topchats.com","adultreviews.com","18tokyo.com",
        "1virgins.com","1girl1camera.com","pridestudios.com","1by-day.com",
        "1800dialadick.com","1passforallsites.com","freeones.com",
        "dreammovies.com","pornhubfillesalope.com","girlygifporn.com",
        "arabicdancevideo.blogspot.com","kellydivine.co","tubepornstars.com",
        "tubepornstars.com","vintagehairy.net","lookatvintage.com","pornorama.com",
        "ass4all.com","cindymovies.com", "onlygirlvideos.com", "rofipot.com",
        "spankwire.com", "arabesexy.com", "megamovie.us", "nakedboobs.net",
        "teencamvids.org", "nudeboobshotpics.com", "sugarbbw.com",
        "sexbotbonnasse.com", "salope.1japonsex.com", "nudematurewomenphotos.com",
        "eroticbeauties.net", "milfs30.com", "freshmatureporn.com", "matureshine.com",
        "wetmaturewhores.com", "mature-galleries.org", "owsmut.com", "webcam.com",
        "maturelle.com", "toppornsites.com", "womenmaturepics.com",
        "all-free-nudes-old-granny-mature-women-xxx.com", "maturepornhub.com",
        "nudeold.com", "uniquesexymoms.com", "nude.oldies.com", "riomature.com",
        "hot-naked-milfs.com", "stifiersmoms.com", "multimature.com",
        "oldhotmoms.com", "matureoracle.com", "hungrymatures.com", "milfous.com",
        "watersweb.com", "eromatures.net", "mom50.com", "maturesinstockings.com",
        "imaturewomen.com", "wetmaturewomen.com", "matureandyoung.com",
        "momshere.com", "riomoms.com", "kissmaturesgo.com", "bitefalm.com",
        "milfionaire.com", "sexymaturethumbs.com", "maturosexy.com", "6mature9.com",
        "hotnakedoldies.com", "reddit.com/r/NSFW411", "reddit.com/r/nsfw",
        "reddit.com/r/suicidegirls", "reddit.com/r/nsfw2",
        "reddit.com/r/TipOfMyPenis", "reddit.com/r/bonermaterial",
        "reddit.com/r/porn", "reddit.com/r/nsfw411", "reddit.com/r/iWantToFuckHer",
        "reddit.com/r/exxxtras", "reddit.com/r/distension",
        "reddit.com/r/bimbofetish", "reddit.com/r/christiangirls",
        "reddit.com/r/cuckold", "reddit.com/r/dirtygaming",
        "reddit.com/r/sexybutnotporn", "reddit.com/r/femalepov",
        "reddit.com/r/omgbeckylookathiscock", "reddit.com/r/milf",
        "reddit.com/r/gonewild30plus", "reddit.com/r/ohnomomwentwild",
        "reddit.com/r/preggoporn", "reddit.com/r/legalteens",
        "reddit.com/r/collegesluts", "reddit.com/r/adorableporn",
        "reddit.com/r/legalteensXXX", "reddit.com/r/gonewild18", "reddit.com/r/18_19",
        "reddit.com/r/just18", "reddit.com/r/realgirls", "reddit.com/r/amateur",
        "reddit.com/r/homemadexxx", "reddit.com/r/AmateurArchives",
        "reddit.com/r/dirtypenpals", "reddit.com/r/FestivalSluts",
        "reddit.com/r/CollegeAmateurs", "reddit.com/r/amateurcumsluts",
        "reddit.com/r/nsfw_amateurs", "reddit.com/r/funwithfriends",
        "reddit.com/r/randomsexiness", "reddit.com/r/amateurporn",
        "reddit.com/r/normalnudes", "reddit.com/r/Camwhores", "reddit.com/r/camsluts",
        "reddit.com/r/SluttyStrangers", "reddit.com/r/GoneWild",
        "reddit.com/r/PetiteGoneWild", "reddit.com/r/gonewildstories",
        "reddit.com/r/GoneWildTube", "reddit.com/r/treesgonewild",
        "reddit.com/r/gonewildaudio", "reddit.com/r/GWNerdy", "reddit.com/r/gonemild",
        "reddit.com/r/altgonewild", "reddit.com/r/gifsgonewild",
        "reddit.com/r/analgw", "reddit.com/r/gonewildsmiles",
        "reddit.com/r/onstageGW", "reddit.com/r/RepressedGoneWild",
        "reddit.com/r/bdsmgw", "reddit.com/r/UnderwearGW", "reddit.com/r/LabiaGW",
        "reddit.com/r/TributeMe", "reddit.com/r/WeddingsGoneWild",
        "reddit.com/r/gwpublic", "reddit.com/r/assholegonewild",
        "reddit.com/r/leggingsgonewild", "reddit.com/r/dykesgonewild",
        "reddit.com/r/gonewild30plus", "reddit.com/r/gonewild18",
        "reddit.com/r/ohnomomwentwild", "reddit.com/r/GWCouples",
        "reddit.com/r/gonewildcouples", "reddit.com/r/gwcumsluts",
        "reddit.com/r/WouldYouFuckMyWife", "reddit.com/r/gonewildcurvy",
        "reddit.com/r/GoneWildplus", "reddit.com/r/BigBoobsGW",
        "reddit.com/r/bigboobsgonewild", "reddit.com/r/AsiansGoneWild",
        "reddit.com/r/gonewildcolor", "reddit.com/r/indiansgonewild",
        "reddit.com/r/workgonewild", "reddit.com/r/GoneWildScrubs",
        "reddit.com/r/NSFW_Snapchat", "reddit.com/r/snapchat_sluts",
        "reddit.com/r/snapleaks", "reddit.com/r/wifesharing", "reddit.com/r/hotwife",
        "reddit.com/r/rule34", "reddit.com/r/hentai", "reddit.com/r/ecchi",
        "reddit.com/r/futanari", "reddit.com/r/hentai_gif", "reddit.com/r/doujinshi",
        "reddit.com/r/overwatch_porn", "reddit.com/r/rule34_comics",
        "reddit.com/r/sex_comics", "reddit.com/r/BDSM", "reddit.com/r/Bondage",
        "reddit.com/r/BDSMcommunity", "reddit.com/r/bdsmgw", "reddit.com/r/blowjobs",
        "reddit.com/r/lipsthatgrip", "reddit.com/r/deepthroat",
        "reddit.com/r/onherknees", "reddit.com/r/blowjobsandwich", "reddit.com/r/ass",
        "reddit.com/r/asstastic", "reddit.com/r/facedownassup",
        "reddit.com/r/assinthong", "reddit.com/r/bigasses", "reddit.com/r/buttplug",
        "reddit.com/r/TheUnderbun", "reddit.com/r/booty", "reddit.com/r/anal",
        "reddit.com/r/analgw", "reddit.com/r/painal", "reddit.com/r/masterofanal",
        "reddit.com/r/buttsharpies", "reddit.com/r/asshole",
        "reddit.com/r/AssholeBehindThong", "reddit.com/r/assholegonewild",
        "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
        "reddit.com/r/boobies", "reddit.com/r/tinytits", "reddit.com/r/TittyDrop",
        "reddit.com/r/burstingout", "reddit.com/r/boltedontits",
        "reddit.com/r/boobbounce", "reddit.com/r/boobs", "reddit.com/r/downblouse",
        "reddit.com/r/homegrowntits", "reddit.com/r/cleavage",
        "reddit.com/r/breastenvy", "reddit.com/r/youtubetitties",
        "reddit.com/r/torpedotits", "reddit.com/r/thehangingboobs",
        "reddit.com/r/BustyPetite", "reddit.com/r/hugeboobs", "reddit.com/r/stacked",
        "reddit.com/r/BigBoobsGW", "reddit.com/r/bigboobsgonewild",
        "reddit.com/r/pokies", "reddit.com/r/ghostnipples", "reddit.com/r/nipples",
        "reddit.com/r/GirlswithNeonHair", "reddit.com/r/shorthairchicks",
        "reddit.com/r/blonde", "reddit.com/r/datgap", "reddit.com/r/girlsinyogapants",
        "reddit.com/r/stockings", "reddit.com/r/legs", "reddit.com/r/thighhighs",
        "reddit.com/r/tightshorts", "reddit.com/r/pussy", "reddit.com/r/rearpussy",
        "reddit.com/r/innie", "reddit.com/r/simps", "reddit.com/r/pelfie",
        "reddit.com/r/LabiaGW", "reddit.com/r/moundofvenus",
        "reddit.com/r/Hotchickswithtattoos", "reddit.com/r/sexyfrex",
        "reddit.com/r/tanlines", "reddit.com/r/oilporn", "reddit.com/r/SexyTummies",
        "reddit.com/r/theratio", "reddit.com/r/fitgirls",
        "reddit.com/r/bodyperfection", "reddit.com/r/gonewildcurvy",
        "reddit.com/r/curvy", "reddit.com/r/gonewildplus", "reddit.com/r/thick",
        "reddit.com/r/juicyasians", "reddit.com/r/voluptuous",
        "reddit.com/r/biggerthanyouthought", "reddit.com/r/jigglefuck",
        "reddit.com/r/chubby", "reddit.com/r/BustyPetite", "reddit.com/r/dirtysmall",
        "reddit.com/r/petitegonewild", "reddit.com/r/xsmallgirls",
        "reddit.com/r/funsized", "reddit.com/r/hugedicktinychick",
        "reddit.com/r/volleyballgirls", "reddit.com/r/Ohlympics",
        "reddit.com/r/celebnsfw", "reddit.com/r/WatchItForThePlot",
        "reddit.com/r/nsfwcelebarchive", "reddit.com/r/celebritypussy",
        "reddit.com/r/oldschoolcoolNSFW", "reddit.com/r/cumsluts",
        "reddit.com/r/GirlsFinishingTheJob", "reddit.com/r/cumfetish",
        "reddit.com/r/amateurcumsluts", "reddit.com/r/cumcoveredfucking",
        "reddit.com/r/cumhaters", "reddit.com/r/thickloads",
        "reddit.com/r/before_after_cumsluts", "reddit.com/r/creampies",
        "reddit.com/r/throatpies", "reddit.com/r/FacialFun",
        "reddit.com/r/cumonclothes", "reddit.com/r/HappyEmbarrassedGirls",
        "reddit.com/r/unashamed", "reddit.com/r/borednignored",
        "reddit.com/r/latinas", "reddit.com/r/AsianHotties",
        "reddit.com/r/AsiansGoneWild", "reddit.com/r/realasians",
        "reddit.com/r/juicyasians", "reddit.com/r/AsianNSFW",
        "reddit.com/r/nextdoorasians", "reddit.com/r/asianporn",
        "reddit.com/r/bustyasians", "reddit.com/r/IndianBabes",
        "reddit.com/r/indiansgonewild", "reddit.com/r/NSFW_Japan",
        "reddit.com/r/javdownloadcenter", "reddit.com/r/kpopfap",
        "reddit.com/r/NSFW_Korea", "reddit.com/r/WomenOfColor",
        "reddit.com/r/darkangels", "reddit.com/r/blackchickswhitedicks",
        "reddit.com/r/ebony", "reddit.com/r/ginger", "reddit.com/r/redheads",
        "reddit.com/r/palegirls", "reddit.com/r/pawg", "reddit.com/r/NSFW_GIF",
        "reddit.com/r/nsfw_gifs", "reddit.com/r/porn_gifs",
        "reddit.com/r/porninfifteenseconds", "reddit.com/r/CuteModeSlutMode",
        "reddit.com/r/60fpsporn", "reddit.com/r/NSFW_HTML5", "reddit.com/r/twingirls",
        "reddit.com/r/groupofnudegirls", "reddit.com/r/nsfwhardcore",
        "reddit.com/r/SheLikesItRough", "reddit.com/r/strugglefucking",
        "reddit.com/r/hugedicktinychick", "reddit.com/r/jigglefuck",
        "reddit.com/r/freeuse", "reddit.com/r/whenitgoesin",
        "reddit.com/r/outercourse", "reddit.com/r/gangbang", "reddit.com/r/breeding",
        "reddit.com/r/pegging", "reddit.com/r/insertions", "reddit.com/r/passionx",
        "reddit.com/r/facesitting", "reddit.com/r/nsfw_plowcam",
        "reddit.com/r/pronebone", "reddit.com/r/fuxtaposition",
        "reddit.com/r/60fpsporn", "reddit.com/r/highresNSFW",
        "reddit.com/r/NSFW_HTML5", "reddit.com/r/incestporn", "reddit.com/r/wincest",
        "reddit.com/r/sarah_xxx", "reddit.com/r/remylacroix",
        "reddit.com/r/Anjelica_Ebbi", "reddit.com/r/lesbians",
        "reddit.com/r/StraightGirlsPlaying", "reddit.com/r/girlskissing",
        "reddit.com/r/mmgirls", "reddit.com/r/dykesgonewild",
        "reddit.com/r/holdthemoan", "reddit.com/r/O_faces", "reddit.com/r/jilling",
        "reddit.com/r/gettingherselfoff", "reddit.com/r/quiver",
        "reddit.com/r/suctiondildos", "reddit.com/r/GirlsHumpingThings",
        "reddit.com/r/forcedorgasms", "reddit.com/r/mmgirls",
        "reddit.com/r/ruinedorgasms", "reddit.com/r/grool", "reddit.com/r/squirting",
        "reddit.com/r/ladybonersgw", "reddit.com/r/massivecock",
        "reddit.com/r/chickflixxx", "reddit.com/r/gaybrosgonewild",
        "reddit.com/r/OnOff", "reddit.com/r/nsfwoutfits",
        "reddit.com/r/Bottomless_Vixens", "reddit.com/r/girlswithglasses",
        "reddit.com/r/lingerie", "reddit.com/r/candidfashionpolice",
        "reddit.com/r/bikinis", "reddit.com/r/collared", "reddit.com/r/tightshorts",
        "reddit.com/r/seethru", "reddit.com/r/sweatermeat", "reddit.com/r/cfnm",
        "reddit.com/r/nsfwcosplay", "reddit.com/r/nsfwcostumes",
        "reddit.com/r/girlsinschooluniforms", "reddit.com/r/WtSSTaDaMiT",
        "reddit.com/r/tightdresses", "reddit.com/r/upskirt", "reddit.com/r/stockings",
        "reddit.com/r/thighhighs", "reddit.com/r/leggingsgonewild",
        "reddit.com/r/assinthong", "reddit.com/r/AssholeBehindThong",
        "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
        "reddit.com/r/ChangingRooms", "reddit.com/r/workgonewild",
        "reddit.com/r/trashyboners", "reddit.com/r/FlashingGirls",
        "reddit.com/r/publicflashing", "reddit.com/r/sexinfrontofothers",
        "reddit.com/r/NotSafeForNature", "reddit.com/r/gwpublic",
        "reddit.com/r/realpublicnudity", "reddit.com/r/socialmediasluts",
        "reddit.com/r/Tgirls", "reddit.com/r/traps", "reddit.com/r/futanari",
        "reddit.com/r/pornvids", "reddit.com/r/nsfw_videos",
        "reddit.com/r/dirtysnapchat", "reddit.com/r/randomactsofblowjob",
        "reddit.com/r/NSFWFunny", "reddit.com/r/confusedboners",
        "reddit.com/r/dirtykikpals", "reddit.com/r/nsfw_wtf",
        "reddit.com/r/randomactsofmuffdive", "reddit.com/r/gore",
        "reddit.com/r/watchpeopledie", "reddit.com/r/popping", "golden-moms.com",
        "madmamas.com", "womanolder.com", "matureland.net", "motherstits.com",
        "unshavenpussies.net", "pornmaturepics.com", "105matures.com",
        "momstaboo.com", "broslingerie.com", "elderly-women.com", "upskirttop.net",
        "bushypussies.net", "amateurmaturewives.com", "universeold.com",
        "unshavengirls.com", "oldernastybitches.com", "maturewant.com",
        "juliepost.com", "mulligansmilfs.com", "bestmaturewomen.com", "riomature.com",
        "mature-orgasm.com", "inlovewithboobs.com", "riotits.net",
        "nakedbustytits.com", "ass-butt.com", "matureladiespics.com",
        "pornmaturewomen.com", "nudemomphotos.com", "secinsurance.com",
        "bigfreemature.com", "mature-women-tube.net", "hotnudematures.com",
        "oldsexybabes.net", "matureasspics.com", "mature30plus.com",
        "matureamour.com", "the momsfucking.net", "boobymilf.com",
        "fantasticwomans.com", "xxxmatureposts.com", "alloldpics.com",
        "lenawethold.com", "mature.nl", "wifezilla.com", "chubbygalls.com",
        "nudematurepics.com", "matureal.com", "thexmilf.com", "cocomilfs.com",
        "zmilfs.com", "wild-matures.com", "horny-matures.net", "grandmabesttube.com",
        "grandmabesttube.com", "bestmilftube.com", "needmilf.com", "girlmature.com",
        "bestmatureclips.com", "lustfuloldies.com", "riomoms.com", "maturehotsex.com",
        "bettermilfs.com", "milfionaire.com", "oldercherry.com", "oldercherry.com",
        "sexymilfpussy.com", "maturepornpics.com", "action36.com", "dianapost.com",
        "babesclub.net", "lovely-mature.net", "bestmaturesthumb.com",
        "myfreemoms.com", "milfatwork.net", "milfgals.net", "olderwomenarchive.com",
        "milfmomspics.com", "pornvideoitaly.com", "stiflersmilfs.com",
        "maturenags.com", "maturenakedsluts.com", "tgpmaturewoman.com",
        "idealwifes.com", "maturewitch.com", "hqmaturemovs.com",
        "mature-women-tube.org", "olderwomentaboo.com", "chocomilf.com",
        "milfparanoia.com", "momsnightjob.com", "matureintros.com", "booloo.com",
        "bigbuttmature.com", "maturetube.com", "mature30-45.com", "pornbox.org",
        "honestpornreviews.com", "crocreview.com", "realitypornsearch.com",
        "paypornlist.net", "rogreviews.com", "thetongue.net", "porninspector.com",
        "backroomfacials.com", "pawg.com", "nailedhard.com", "fuckteamfive.com",
        "bangbros18teens.com", "partyofthree.com", "latinarampage.com",
        "backroommilf.com", "canhescore.com", "mujeresculonas.net", "xkeezmovies.com",
        "bangpov.com", "bang.com", "porndoe.com", "blowjobninjas.com", "mrpornx.com",
        "mydirtymaid.net", "stepmomvideos.com", "rabbitsreviews.com", "empflix.com",
        "boobpedia.com", "dorminvasion.com", "easyporn.tv", "rexmag.com", "fux.com",
        "pornadept.com", "mylifeinbrazil.com", "yespornpleae.com", "ultrahorny.com",
        "momishorny.com", "bangoncasting.com", "bangbros-free.com", "720porn.net",
        "funvidporn.com", "bangpass.com", "siterip4fun.com", "bangbros.com",
        "porntube.com", "youjizz.com", "redtube.com", "xvideos.com", "xhamster.com",
        "xnxx.com", "hclips.com", "porn.com", "tnaflix.com",
        "tube8.com", "hd21.com", "newhd.xxx", "spankbang.com", "drtuber.com",
        "spankwire.com", "keezmovies.com", "nuvid.com", "sunporno.com",
        "bravotube.net", "bravoteens.com", "drtuber.com", "mylust.com",
        "overthumbs.com", "palmtube.com", "pornhd.com", "porn300.com", "sexvid.xxx",
        "xxxbunker.com", "mofosex.com", "xbabe.com", "updatetube.com", "befuck.com",
        "bravoerotica.com", "masseurporn.com", "hdmovz.com", "pornrox.com",
        "pornmaki.com", "pornid.xxx", "inxporn.com", "slutload.com", "proporn.com",
        "fakeporn.tv", "pornhost.com", "handjobhub.com", "vpornvideos.com",
        "myxvids.com", "dansmovies.com", "fapdu.com", "rude.com",
        "topfreepornvideos.com", "freudbox.com", "pornheed.com", "hdporn.net",
        "orgasm.com", "pornrabbit.com", "madthumbs.com", "fux.com", "eroxia.com",
        "deviantclip.com", "xxvids.net", "h2porn.com", "apetube.com", "metaporn.com",
        "elephanttube.com", "long.xxx", "pornerbros.com", "iporntv.net", "pron.tv",
        "pornplanner.com", "mypornbible.com", "badjojo.com", "findtubes.com",
        "lasmejoreswebsporno.com/en", "pornmd.com", "nudevista.com",
        "it.bing.com/videos/search?q=por",
        "video.search.yahoo.com/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=ZaF57phvPYQ,138531013",
        "video.search.yahoo.com/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=t2freeITUJs,1526679329&fr2=p%3As%2Cv%3Av&save=0",
        "adultvideofinder.com", "awejmp.com", "imlive.com", "evilangellive.com",
        "awejmp.com", "joyourself.com", "xlovecam.com", "cams.com", "pornication.com",
        "delhisexchat.com", "sexier.com", "secure.vividcams.com", "privatefeeds.com",
        "streamate.com", "slutroulette.com", "t.hrtya.com", "watchmyexgf.net",
        "watchmygf.cc", "fantasti.cc", "watchmygf.me", "iknowthatgirl.com",
        "daredorm.com", "crazycollegegfs.com", "analized.com", "punishtube.com",
        "stufferdb.com", "88gals.com", "sexforums.com/gallery", "apina.biz",
        "babe-lounge.com", "fuskator.com", "gotporn.com", "arabianchicks.com",
        "extremetube.com", "fetishpapa.com", "fuckler.com", "fantasti.cc",
        "bdsmstreak.com", "zzcartoon.com", "animeidhentai.com", "hentaihaven.org",
        "simply-hentai.com", "hentaigasm.com", "fakku.net", "gelbooru.com",
        "hentaipulse.com", "porcore.com", "hentaischool.com",
        "chan.sankakucomplex.com", "hentai-foundry.com", "babesrater.com",
        "punchpin.com", "lustpin.com", "sexlikereal.com", "vrsmash.com", "stasyq.com",
        "mobilevrxxx.com", "realitylovers.com", "myporngay.com", "zzgays.com",
        "gay-lounge.net", "justusboys.com", "iptorrents.com/torrents", "rarbg.com",
        "pussytorrents.org", "porn.com", "yourdailypornstars.com",
        "bestpornstardb.com", "babepedia.com", "kindgirls.com", "playindiansex.com",
        "playindianporn.com", "viewdesisex.com", "hotsouthindiansex.com",
        "watchindianporn.net", "xpaja.net", "lesbian8.com", "kirtu.com",
        "velamma.com", "nutaku.net", "69games.xxx", "gamcore.com",
        "assist.lifeselector.com", "playforceone.com", "brazzersnetwork.com",
        "wct.link", "rk.com", "digitalplayground.com", "mofosnetwork.com",
        "gfrevenge.com", "twistysnetwork.com", "teamskeet.com", "bangbrosnetwork.com",
        "iyalc.com", "ddfnetwork.com", "braincash.com", "iyalc.com", "videosz.com",
        "hustler.com", "premiumbukkake.com", "javhd.com", "pornprosnetwork.com",
        "perfectgonzo.com", "alljapanesepass.com", "momsbangteens.com",
        "wickedpictures.com", "puffynetwork.com", "18videoz.com", "nubiles.net",
        "kinkyfamily.com", "allofgfs.com", "filf.com", "dorcelclub.com",
        "best-paypornsites.com", "nakednews.com", "playboy.com", "forumophilia.com",
        "jdforum.net", "freeones.com", "peachyforum.com", "sexyrealsexdolls.com",
        "spklmis.com", "toppornsites.com", "Tubegalore.com", "gaymaletube.com",
        "iXXX.com", "1piecehentai.com", "2hentai.com", "2th.com", "4chan.com",
        "69ani.com", "8muses.com", "aerisdies.com", "allhentai.com",
        "animefootfetish.com", "animehentaimangas.com", "animetor.com",
        "animephile.com", "aryion.com", "asmhentai.com", "atsuifeet.com", "baidu.com",
        "baixarhentai.com", "bamtoki.com", "bangcartoons.com", "baramangaonline.com",
        "bbotoon.com", "bobx.com", "brasilhentai.com", "clickhentai.com",
        "codegeassxxx.com", "colorhentaimangas.com", "comicsfromhell.com",
        "comicsporno.com", "comicspornogratis.com", "comixhere.com",
        "deliciousdoujinshi.com", "dochentai.com", "doujin2.com", "doujin-th.com",
        "doujindaily.com", "doujinland.com", "doujinlife.com",
        "doujinloverandgiver.com", "doujinmode.com", "doujinpage.com",
        "doujinreader.com", "doujinroom.com", "doujins.com", "doujinshentai.com",
        "doujinshi rocks.com", "doujinshihentai.com", "doujinx.com", "e-hentai.com",
        "ecchitail.com", "ero-senin.com", "erolord.com", "eromanga-sokuhou.com",
        "eshentaionline.com.com", "exhentai.com", "fapdu.com", "ff10hentai.com",
        "ff12hentai.com", "ff7hentai.com", "finalxxxfantasy.com", "furaffinity.com",
        "futahentai.com", "futanarispash.com", "g6hentai.com", "gs-uploader.com",
        "gurrenhentai.com", "h-manga moe.com", "hakihome.com", "hbrowse.com",
        "hcomicbook.com", "hdarkzone.com", "hellven.com", "hentai-ddl.com",
        "hentai-free.com", "hentai-id.com", "hentai-ita.com", "hentai-manga.com",
        "hentaicafe.com", "hentaims.com", "hentaipink.com", "hentaltl.com",
        "hental2read.com", "hentai4me.com", "hentai4doujin.com", "hentai4manga.com",
        "hentai4u.com", "hentai666.com", "hentaibeast.com", "hentaiboxfr.com",
        "hentaibox.com", "hentaibunny.com", "hentaibusty.com", "hentaichan.com",
        "hentaicloud.com", "hentaicorner.com", "hentaifamed.com", "hentaifield.com",
        "hentaifox.com", "hentaifr.com", "hentaifromhell.com", "hentaigamech.com",
        "hentaigratuit.com", "hentaihere.com", "hentaihouse.com", "hentaihousext.com",
        "hentaihunt.com", "hentaiiXXX.com", "hentaijuggs.com", "hentailx.com",
        "hentailxers.com", "hentaimangabiz.com", "hentaimangaonline.com",
        "hentaimangaz.com", "hentainesia.com", "hentaiporns.com", "hentairead.com",
        "henairing.com", "hentairules.com", "hentaischool.com", "hentaisd.com",
        "hentaistack.com", "hentaivn.com", "hentype.com", "hgamecg.com", "hhhhhh.com",
        "high-hentai.com", "hime-doujins.com", "hipercool.com", "hitomi.com",
        "hmangasearcher.com", "hotdhentai.com", "ihentaimanga.com", "imagefap.com",
        "incesthentai.com", "junkuchan.com", "kimi-h.com", "komikhentai.com",
        "lolhentai.com", "lookmanga.com", "lovehentaimanga.com", "luscious.com",
        "ohentai.com", "mahenku.com", "manga12.com", "mangaboxes.com", "mangafap.com",
        "mangakawaiifeet.com", "manganude.com", "mangaray.com", "mangaseries.com",
        "mangawindow.com", "mapussy.com", "massivehentai.com", "maturemangas.com",
        "megahentaicomics.com", "milkyhentai.com", "minihentai.com",
        "muchodoujins.com", "muchohentai.com", "multporn.com", "mydoujins.com",
        "myhentaicomics.com", "myreadingmanga.com", "narutohentaigalleries.com",
        "nhentai.com", "nude-moon.com", "nxt-comics.com", "ohtori.com",
        "omorashi.com", "overwatchhentaidb.com", "palcomix.com", "pbxwwoec.com",
        "personahentai.com", "perveden.com", "pinayacenter.com", "plentyofhentai.com",
        "pomfpomf.com", "porncomics.com", "porncmix.com", "pornocomics.com",
        "pornsource.com", "pornxxxcomics.com", "primehentai.com", "proxer.com",
        "pururin.com", "r34comics.com", "readhentaidoujinshi.com",
        "readhentaimanga.com", "readincesthentai.com", "readmangahentai.com",
        "revistasequadrinhos.com", "ryuutama.com", "sextgem.com", "shentai.com",
        "simply-hentai.com", "sinnergate.com", "smdc-translations.com",
        "sohentai.com", "submanga.com", "sukahentai.com", "svscomics.com",
        "sweetyaoiparadise.com", "thedoujin.com", "thehentaiworld.com",
        "tmohentai.com", "truyen18.com", "tsumino.com", "underworld-scans.com",
        "fapworks.com", "vanillahentai.com", "ver-manga.com", "vercomicsporno.com",
        "vesquare.com", "watchhentaistream.com", "world-hentai.com", "xcartx.com",
        "xcomics4you.com", "xxcomics.com", "xxxyuna.com", "yaoichan.com",
        "yaoifox.com", "yaoihavenreborn.com", "yuri-ism.com", "yurimanga.com",
        "zizki.com", "zkomik.com", "findtubes.com", "1indiansex.net", "3rat.com",
        "4hen.com", "africansexvideos.net", "bananabunny.com", "cutepornvideos.com",
        "desimurga.com", "desisexclips.com", "dslady.com", "eroticperfection.com",
        "porn.com", "porn.org", "gaypormium.com", "gracefulnudes.com",
        "hot-dates.info", "hqlinks.net", "indiansex4u.com.xxx", "jav-porn.net",
        "legalporno.com", "luboeporno.com", "pinkythekinky.com", "sexsex.hu",
        "sexxxi.com", "semale.asia", "thefreecamsecret.com", "momsteachsex.com",
        "petardas.com", "89.com", "alohatube.com", "babosas.com", "callboyindia.com",
        "cam4.co", "cam4.com", "cam4.in", "youpornru.com", "cholotube.com", "cliphunter.com",
        "culosgratis.com", "cumlouder.com", "darering.com", "flirt4free.com",
        "fuq.com", "hairy.com", "labatidora.net", "leche69.com", "livejasmin.com",
        "locasporfollar.com", "lushstories.com", "mc-nudes.com", "myfreecams.com",
        "naughty.com", "penguinvids.com", "perfectgirls.com", "perucaseras.com",
        "pinkworld.com", "playvid.com", "puritanas.com", "rk.com",
        "roundandbrown.com", "truthordarepics.com", "videosdemadurasx.com",
        "x-ho.com", "xixx.com", "xtube.com", "xvideosnacional.com", "purebbwtube.com",
        "babes.com", "fotosmujeres.pibones.com", "rubber-kingdom.com",
        "savitabhabhi.mobi", "pinkvisualtgp.com", "antarvasna.com", "hot-gifz.com",
        "lechecaliente.com", "parejasfollando.es", "flirthookup.com", "cerdas.com",
        "chaturbate.com", "ledauphine.com", "freex.mobi", "gokabyle.com",
        "bdenjoymore.blogspot.com", "petardas.com", "conejox.com", "voyeurpipi.com",
        "gouines.pornoxxxi.net", "arabebaise.com", "ohasiatique.com", "poringa.net",
        "lisaannlovers11.tumblr.com", "h33t.to", "marocainenue.com",
        "gorgeousladies.com", "fille-nue-video.com", "teensnow.com",
        "theofficiallouisejenson.co", "yourather.com", "bootlust.com",
        "toonztube.com", "top-chatroulette.com", "videosfilleschaudes.com",
        "fillechaude.org", "femmesmuresx.net", "liberteenage.com", "coffeetube.com",
        "awesomeellalove.tumblr.com", "xnxxgifs.com", "saoulbadjojo.com",
        "beurettehot.net", "woodstockreborn.tumblr.com",
        "belles-femmes-arabes.blogspot.com", "xgouines.com", "couleurlvoirce.com",
        "3animalsextube.com", "moncloutube.net", "sexocean.com", "femdomempire.com",
        "babosas.co", "giude-asie.com", "beauxcul.com", "maghrebinnes.xl.cx",
        "xnxx-free.net", "xnxx.vc", "es.bravotube.net", "rubias19.com",
        "xxl.onxille.com", "asiataique-femme.com", "masalopeblack.com",
        "beautiful-nude-tens-exposed.tur", "pormhub.com", "cochonnevideosx.com", "videosanalesx.com",
        "dorceltv.xn.pl", "salope-marocaine.com", "jeunette18.com", "redtuve.com",
        "les-grosses.net", "yasminramos.com", "tukif.com", "adultwork.com",
        "hairy.com", "tendance-lesbienne.com", "indiansexstories.net", "eros.com",
        "7dog.com", "vivthomas.com", "teensnowxvideos.com",
        "x-art.com","chaturbate.com","pinkworld.com","pandamovies.com","muyzorras.com","uplust.com",
        "shemales.com","bigboobsalert.com","culx.org","falconstudios.com","nautilix.com","ovideox.com",
        "herbalviagraworld.com","primecurves.com","xbabe.com","webpnudes.com",
        "smutty.com","naughtyamerica.com","faketaxi.com","momjoi.com","dreammovies.com", "swallowed.com",
        "asspoint.com", "bobs-tube.com", "4tube.com", "canalporno.com", "eporner.com",
        "hdpornt.com", "kink.com", "milffox.com", "mypornstarbook.com", "xshare.com"
    };

//    static Map<String, Boolean> dict = new HashMap<String, Boolean>();
//
//
//    public static void init() {
//        for (int i = 0; i < pornLinks.length; i++) {
//            dict.put(pornLinks[i],true);
//        }
//    }

}
