// PorNo! Android
// porNo.java
// @author Vivek Bhookya

package us.mrvivacio.porno;

import java.util.HashMap;
import java.util.Map;

public class porNo {
    static String [] pornLinks = {
        ".xxx",".adult",".porn","anissa-kate","anissakate","manyvids",
        ".sex","jizzman.com","tube8","barelist.com", "hugesex.tv","xnxx.com",
        "pornhub.com","youporn.com","thefappening.pro","lezbiyenporno.org",
        "godfatherporn.com","hotgirlclub.com","m.perfectgirls.net","mikeinbrazil.com",
        "nitroflare-porn.com","pornfack.com","porngals4.com","pornve.com","pornzog.com",
        "sexuria.to","straight.fleshbot.com",
        "ulsexvideo.com", "mobile.bangbros.com","uviporn.com","vporn.com","xpornplease.com","xxhdporn.com",
        "adultfreex.com","dirtypornvids.com","devporn.net","forbiddenplaygroundxxx.com",
        "devporn.net","123porn.me","devporn.net","fapvibe.com","redwap.me","xhamster.news",
        "excitemii.com", "tubsexer.com","fapality.com","vip-pornfilms.com","adultbliss.net","3d-porn.us",
        "naughtyamericavr.com","1sexporn.com","juggsjoy.com",
        "m.fxporn.net","pornfactor.net","pornoxo.com","teamskeet.com","ultrahdporn.eu","vepornhd.club",
        "vixvids.to","xporn.com.es","anybunny.mobi",
        "barscapital.ru","bb-magazine.ru","fullhdpornmovie.com","hdpornstarz.com","hotnudephoto.com",
        "jizzboom.com","nesaporn.mobi","nudedesigirls.net",
        "pornpics.com","pornsexerotica.com","porntubeclub.com","rajwap.xyz","redhdtube.xxx","redhub.co",
        "sexpussynude.com","smutindia.com",
        "teenpornvideo.xxx","upornia.com","weliketosuck.us","xxx-picture.com","xxxymovies.com",
        "3movs.com","4tube.com",
        "pornhd.com","rushporn.com","spankbang.com","thumbzilla.com","porno-hub.com","hd-porn",
        "redtube.com","xtapes.to",
        ".porno","vid27.com",".sx", "porno.", "xnxx.com", "hugesex.tv", ".sexy","swallowed.com", "newsexxxx.com",".sucks",".wang","puba.com",
        "evanotty.com","xfreehd.com", ".webcam",".exposed", "pornhub.com", "foxporn.com","realgfporn.com","34jpornstar.us","sex3.com","sexu.com",
        "titsbox.com","tryboobs.com","tubedupe.com","tubeon.mobi","porn4days", "tubepornclassic.com","pornav.net","tubous.com","nevid.us","viptube.com",
        "vivatube.com","vivud.com","voyeurhit.com","vporn.com","wetplace.com",
        "winporn.com","xcafe.com","funnyjunk.com/nsfw","xozilla.com","xxxdan.com", "yeptube.com","yourlust.com","ah-me.com","analdin.com",
        "dirtypornivds.com","zemporn.com","stocking-tease.com", "pornvideohunter.com","zmovs.com","fuck55.net","3gpkings.com","kompoz.me",
        "realitykings.com","pornolaba.com","foxporns.com","anyporn.com", "videosexarchive.com","redwap.me","avelip.com","anysex.com","megacam.me",
        "longsextubes.com","bustymomsvideo.com","clipeu.com","brazzers.com", "bangbus.com","assparade.com","tuboff.com","erome.com",
        "monstersofcock.com","porno-wonder.com","siska.tv","gofucker.com", "pornalized.com","pornoid.com","pornoxo.com","pornpy.com",
        "pornsharing.com","pornwatchers.com","pornxs.com","bigmouthfuls.com", "bigtitsroundasses.com","chaturbate.com","tugjobs.com","flyingjizz.com",
        "jizzbunker.com","fap18.net","euphoriaporn.com","japan-whores.com", "pinkrod.com","uploporn.com","hdzog.com","iceporn.com","hotmovs.com",
        "hellporno.com","bigtitcreampie.com","camvideos.com","txxx.com",
        "eskimotube.com","beeg.com","milfsoup.com","flyflv.com", "brownbunnies.com","mrporngeek.porn","upornia.com","bangbrostubehd.com",
        "adultdvdempire.com","bangbrosclips.com","faapy.com","porndish.com",
        "magicalfeet.com","topchats.com","adultreviews.com","18tokyo.com",
        "1virgins.com","1girl1camera.com","pridestudios.com","1by-day.com",
        "1800dialadick.com","1passforallsites.com","freeones.com",
        "dreammovies.com","pornhubfillesalope.com","girlygifporn.com",
        "arabicdancevideo.blogspot.com","kellydivine.co","tubepornstars.com",
        "tubepornstars.com","vintagehairy.net","lookatvintage.com","pornorama.com",
        "ass4all.com","cindymovies.com", "onlygirlvideos.com", "rofipot.com",
        "spankwire.com", "arabesexy.com", "megamovie.us", "nakedboobs.net",
        "teencamvids.org", "nudeboobshotpics.com", "sugarbbw.com",
        "sexbotbonnasse.com", "salope.1japonsex.com", "nudematurewomenphotos.com",
        "eroticbeauties.net", "milfs30.com", "freshmatureporn.com", "matureshine.com",
        "wetmaturewhores.com", "mature-galleries.org", "owsmut.com", "webcam.com",
        "maturelle.com", "toppornsites.com", "womenmaturepics.com",
        "all-free-nudes-old-granny-mature-women-xxx.com", "maturepornhub.com",
        "nudeold.com", "uniquesexymoms.com", "nude.oldies.com", "riomature.com",
        "hot-naked-milfs.com", "stifiersmoms.com", "multimature.com",
        "oldhotmoms.com", "matureoracle.com", "hungrymatures.com", "milfous.com",
        "watersweb.com", "eromatures.net", "mom50.com", "maturesinstockings.com",
        "imaturewomen.com", "wetmaturewomen.com", "matureandyoung.com",
        "momshere.com", "riomoms.com", "kissmaturesgo.com", "bitefalm.com",
        "milfionaire.com", "sexymaturethumbs.com", "maturosexy.com", "6mature9.com",
        "hotnakedoldies.com", "reddit.com/r/NSFW411", "reddit.com/r/nsfw",
        "reddit.com/r/suicidegirls", "reddit.com/r/nsfw2",
        "reddit.com/r/TipOfMyPenis", "reddit.com/r/bonermaterial",
        "reddit.com/r/porn", "reddit.com/r/nsfw411", "reddit.com/r/iWantToFuckHer",
        "reddit.com/r/exxxtras", "reddit.com/r/distension",
        "reddit.com/r/bimbofetish", "reddit.com/r/christiangirls",
        "reddit.com/r/cuckold", "reddit.com/r/dirtygaming",
        "reddit.com/r/sexybutnotporn", "reddit.com/r/femalepov",
        "reddit.com/r/omgbeckylookathiscock", "reddit.com/r/milf",
        "reddit.com/r/gonewild30plus", "reddit.com/r/ohnomomwentwild",
        "reddit.com/r/preggoporn", "reddit.com/r/legalteens",
        "reddit.com/r/collegesluts", "reddit.com/r/adorableporn",
        "reddit.com/r/legalteensXXX", "reddit.com/r/gonewild18", "reddit.com/r/18_19",
        "reddit.com/r/just18", "reddit.com/r/realgirls", "reddit.com/r/amateur",
        "reddit.com/r/homemadexxx", "reddit.com/r/AmateurArchives",
        "reddit.com/r/dirtypenpals", "reddit.com/r/FestivalSluts",
        "reddit.com/r/CollegeAmateurs", "reddit.com/r/amateurcumsluts",
        "reddit.com/r/nsfw_amateurs", "reddit.com/r/funwithfriends",
        "reddit.com/r/randomsexiness", "reddit.com/r/amateurporn",
        "reddit.com/r/normalnudes", "reddit.com/r/Camwhores", "reddit.com/r/camsluts",
        "reddit.com/r/SluttyStrangers", "reddit.com/r/GoneWild",
        "reddit.com/r/PetiteGoneWild", "reddit.com/r/gonewildstories",
        "reddit.com/r/GoneWildTube", "reddit.com/r/treesgonewild",
        "reddit.com/r/gonewildaudio", "reddit.com/r/GWNerdy", "reddit.com/r/gonemild",
        "reddit.com/r/altgonewild", "reddit.com/r/gifsgonewild",
        "reddit.com/r/analgw", "reddit.com/r/gonewildsmiles",
        "reddit.com/r/onstageGW", "reddit.com/r/RepressedGoneWild",
        "reddit.com/r/bdsmgw", "reddit.com/r/UnderwearGW", "reddit.com/r/LabiaGW",
        "reddit.com/r/TributeMe", "reddit.com/r/WeddingsGoneWild",
        "reddit.com/r/gwpublic", "reddit.com/r/assholegonewild",
        "reddit.com/r/leggingsgonewild", "reddit.com/r/dykesgonewild",
        "reddit.com/r/gonewild30plus", "reddit.com/r/gonewild18",
        "reddit.com/r/ohnomomwentwild", "reddit.com/r/GWCouples",
        "reddit.com/r/gonewildcouples", "reddit.com/r/gwcumsluts",
        "reddit.com/r/WouldYouFuckMyWife", "reddit.com/r/gonewildcurvy",
        "reddit.com/r/GoneWildplus", "reddit.com/r/BigBoobsGW",
        "reddit.com/r/bigboobsgonewild", "reddit.com/r/AsiansGoneWild",
        "reddit.com/r/gonewildcolor", "reddit.com/r/indiansgonewild",
        "reddit.com/r/workgonewild", "reddit.com/r/GoneWildScrubs",
        "reddit.com/r/NSFW_Snapchat", "reddit.com/r/snapchat_sluts",
        "reddit.com/r/snapleaks", "reddit.com/r/wifesharing", "reddit.com/r/hotwife",
        "reddit.com/r/rule34", "reddit.com/r/hentai", "reddit.com/r/ecchi",
        "reddit.com/r/futanari", "reddit.com/r/hentai_gif", "reddit.com/r/doujinshi",
        "reddit.com/r/overwatch_porn", "reddit.com/r/rule34_comics",
        "reddit.com/r/sex_comics", "reddit.com/r/BDSM", "reddit.com/r/Bondage",
        "reddit.com/r/BDSMcommunity", "reddit.com/r/bdsmgw", "reddit.com/r/blowjobs",
        "reddit.com/r/lipsthatgrip", "reddit.com/r/deepthroat",
        "reddit.com/r/onherknees", "reddit.com/r/blowjobsandwich", "reddit.com/r/ass",
        "reddit.com/r/asstastic", "reddit.com/r/facedownassup",
        "reddit.com/r/assinthong", "reddit.com/r/bigasses", "reddit.com/r/buttplug",
        "reddit.com/r/TheUnderbun", "reddit.com/r/booty", "reddit.com/r/anal",
        "reddit.com/r/analgw", "reddit.com/r/painal", "reddit.com/r/masterofanal",
        "reddit.com/r/buttsharpies", "reddit.com/r/asshole",
        "reddit.com/r/AssholeBehindThong", "reddit.com/r/assholegonewild",
        "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
        "reddit.com/r/boobies", "reddit.com/r/tinytits", "reddit.com/r/TittyDrop",
        "reddit.com/r/burstingout", "reddit.com/r/boltedontits",
        "reddit.com/r/boobbounce", "reddit.com/r/boobs", "reddit.com/r/downblouse",
        "reddit.com/r/homegrowntits", "reddit.com/r/cleavage",
        "reddit.com/r/breastenvy", "reddit.com/r/youtubetitties",
        "reddit.com/r/torpedotits", "reddit.com/r/thehangingboobs",
        "reddit.com/r/BustyPetite", "reddit.com/r/hugeboobs", "reddit.com/r/stacked",
        "reddit.com/r/BigBoobsGW", "reddit.com/r/bigboobsgonewild",
        "reddit.com/r/pokies", "reddit.com/r/ghostnipples", "reddit.com/r/nipples",
        "reddit.com/r/GirlswithNeonHair", "reddit.com/r/shorthairchicks",
        "reddit.com/r/blonde", "reddit.com/r/datgap", "reddit.com/r/girlsinyogapants",
        "reddit.com/r/stockings", "reddit.com/r/legs", "reddit.com/r/thighhighs",
        "reddit.com/r/tightshorts", "reddit.com/r/pussy", "reddit.com/r/rearpussy",
        "reddit.com/r/innie", "reddit.com/r/simps", "reddit.com/r/pelfie",
        "reddit.com/r/LabiaGW", "reddit.com/r/moundofvenus",
        "reddit.com/r/Hotchickswithtattoos", "reddit.com/r/sexyfrex",
        "reddit.com/r/tanlines", "reddit.com/r/oilporn", "reddit.com/r/SexyTummies",
        "reddit.com/r/theratio", "reddit.com/r/fitgirls",
        "reddit.com/r/bodyperfection", "reddit.com/r/gonewildcurvy",
        "reddit.com/r/curvy", "reddit.com/r/gonewildplus", "reddit.com/r/thick",
        "reddit.com/r/juicyasians", "reddit.com/r/voluptuous",
        "reddit.com/r/biggerthanyouthought", "reddit.com/r/jigglefuck",
        "reddit.com/r/chubby", "reddit.com/r/BustyPetite", "reddit.com/r/dirtysmall",
        "reddit.com/r/petitegonewild", "reddit.com/r/xsmallgirls",
        "reddit.com/r/funsized", "reddit.com/r/hugedicktinychick",
        "reddit.com/r/volleyballgirls", "reddit.com/r/Ohlympics",
        "reddit.com/r/celebnsfw", "reddit.com/r/WatchItForThePlot",
        "reddit.com/r/nsfwcelebarchive", "reddit.com/r/celebritypussy",
        "reddit.com/r/oldschoolcoolNSFW", "reddit.com/r/cumsluts",
        "reddit.com/r/GirlsFinishingTheJob", "reddit.com/r/cumfetish",
        "reddit.com/r/amateurcumsluts", "reddit.com/r/cumcoveredfucking",
        "reddit.com/r/cumhaters", "reddit.com/r/thickloads",
        "reddit.com/r/before_after_cumsluts", "reddit.com/r/creampies",
        "reddit.com/r/throatpies", "reddit.com/r/FacialFun",
        "reddit.com/r/cumonclothes", "reddit.com/r/HappyEmbarrassedGirls",
        "reddit.com/r/unashamed", "reddit.com/r/borednignored",
        "reddit.com/r/latinas", "reddit.com/r/AsianHotties",
        "reddit.com/r/AsiansGoneWild", "reddit.com/r/realasians",
        "reddit.com/r/juicyasians", "reddit.com/r/AsianNSFW",
        "reddit.com/r/nextdoorasians", "reddit.com/r/asianporn",
        "reddit.com/r/bustyasians", "reddit.com/r/IndianBabes",
        "reddit.com/r/indiansgonewild", "reddit.com/r/NSFW_Japan",
        "reddit.com/r/javdownloadcenter", "reddit.com/r/kpopfap",
        "reddit.com/r/NSFW_Korea", "reddit.com/r/WomenOfColor",
        "reddit.com/r/darkangels", "reddit.com/r/blackchickswhitedicks",
        "reddit.com/r/ebony", "reddit.com/r/ginger", "reddit.com/r/redheads",
        "reddit.com/r/palegirls", "reddit.com/r/pawg", "reddit.com/r/NSFW_GIF",
        "reddit.com/r/nsfw_gifs", "reddit.com/r/porn_gifs",
        "reddit.com/r/porninfifteenseconds", "reddit.com/r/CuteModeSlutMode",
        "reddit.com/r/60fpsporn", "reddit.com/r/NSFW_HTML5", "reddit.com/r/twingirls",
        "reddit.com/r/groupofnudegirls", "reddit.com/r/nsfwhardcore",
        "reddit.com/r/SheLikesItRough", "reddit.com/r/strugglefucking",
        "reddit.com/r/hugedicktinychick", "reddit.com/r/jigglefuck",
        "reddit.com/r/freeuse", "reddit.com/r/whenitgoesin",
        "reddit.com/r/outercourse", "reddit.com/r/gangbang", "reddit.com/r/breeding",
        "reddit.com/r/pegging", "reddit.com/r/insertions", "reddit.com/r/passionx",
        "reddit.com/r/facesitting", "reddit.com/r/nsfw_plowcam",
        "reddit.com/r/pronebone", "reddit.com/r/fuxtaposition",
        "reddit.com/r/60fpsporn", "reddit.com/r/highresNSFW",
        "reddit.com/r/NSFW_HTML5", "reddit.com/r/incestporn", "reddit.com/r/wincest",
        "reddit.com/r/sarah_xxx", "reddit.com/r/remylacroix",
        "reddit.com/r/Anjelica_Ebbi", "reddit.com/r/lesbians",
        "reddit.com/r/StraightGirlsPlaying", "reddit.com/r/girlskissing",
        "reddit.com/r/mmgirls", "reddit.com/r/dykesgonewild",
        "reddit.com/r/holdthemoan", "reddit.com/r/O_faces", "reddit.com/r/jilling",
        "reddit.com/r/gettingherselfoff", "reddit.com/r/quiver",
        "reddit.com/r/suctiondildos", "reddit.com/r/GirlsHumpingThings",
        "reddit.com/r/forcedorgasms", "reddit.com/r/mmgirls",
        "reddit.com/r/ruinedorgasms", "reddit.com/r/grool", "reddit.com/r/squirting",
        "reddit.com/r/ladybonersgw", "reddit.com/r/massivecock",
        "reddit.com/r/chickflixxx", "reddit.com/r/gaybrosgonewild",
        "reddit.com/r/OnOff", "reddit.com/r/nsfwoutfits",
        "reddit.com/r/Bottomless_Vixens", "reddit.com/r/girlswithglasses",
        "reddit.com/r/lingerie", "reddit.com/r/candidfashionpolice",
        "reddit.com/r/bikinis", "reddit.com/r/collared", "reddit.com/r/tightshorts",
        "reddit.com/r/seethru", "reddit.com/r/sweatermeat", "reddit.com/r/cfnm",
        "reddit.com/r/nsfwcosplay", "reddit.com/r/nsfwcostumes",
        "reddit.com/r/girlsinschooluniforms", "reddit.com/r/WtSSTaDaMiT",
        "reddit.com/r/tightdresses", "reddit.com/r/upskirt", "reddit.com/r/stockings",
        "reddit.com/r/thighhighs", "reddit.com/r/leggingsgonewild",
        "reddit.com/r/assinthong", "reddit.com/r/AssholeBehindThong",
        "reddit.com/r/girlsinyogapants", "reddit.com/r/yogapants",
        "reddit.com/r/ChangingRooms", "reddit.com/r/workgonewild",
        "reddit.com/r/trashyboners", "reddit.com/r/FlashingGirls",
        "reddit.com/r/publicflashing", "reddit.com/r/sexinfrontofothers",
        "reddit.com/r/NotSafeForNature", "reddit.com/r/gwpublic",
        "reddit.com/r/realpublicnudity", "reddit.com/r/socialmediasluts",
        "reddit.com/r/Tgirls", "reddit.com/r/traps", "reddit.com/r/futanari",
        "reddit.com/r/pornvids", "reddit.com/r/nsfw_videos",
        "reddit.com/r/dirtysnapchat", "reddit.com/r/randomactsofblowjob",
        "reddit.com/r/NSFWFunny", "reddit.com/r/confusedboners",
        "reddit.com/r/dirtykikpals", "reddit.com/r/nsfw_wtf",
        "reddit.com/r/randomactsofmuffdive", "reddit.com/r/gore",
        "reddit.com/r/watchpeopledie", "reddit.com/r/popping", "golden-moms.com",
        "madmamas.com", "womanolder.com", "matureland.net", "motherstits.com",
        "unshavenpussies.net", "pornmaturepics.com", "105matures.com",
        "momstaboo.com", "broslingerie.com", "elderly-women.com", "upskirttop.net",
        "bushypussies.net", "amateurmaturewives.com", "universeold.com",
        "unshavengirls.com", "oldernastybitches.com", "maturewant.com",
        "juliepost.com", "mulligansmilfs.com", "bestmaturewomen.com", "riomature.com",
        "mature-orgasm.com", "inlovewithboobs.com", "riotits.net",
        "nakedbustytits.com", "ass-butt.com", "matureladiespics.com",
        "pornmaturewomen.com", "nudemomphotos.com", "secinsurance.com",
        "bigfreemature.com", "mature-women-tube.net", "hotnudematures.com",
        "oldsexybabes.net", "matureasspics.com", "mature30plus.com",
        "matureamour.com", "the momsfucking.net", "boobymilf.com",
        "fantasticwomans.com", "xxxmatureposts.com", "alloldpics.com",
        "lenawethold.com", "mature.nl", "wifezilla.com", "chubbygalls.com",
        "nudematurepics.com", "matureal.com", "thexmilf.com", "cocomilfs.com",
        "zmilfs.com", "wild-matures.com", "horny-matures.net", "grandmabesttube.com",
        "grandmabesttube.com", "bestmilftube.com", "needmilf.com", "girlmature.com",
        "bestmatureclips.com", "lustfuloldies.com", "riomoms.com", "maturehotsex.com",
        "bettermilfs.com", "milfionaire.com", "oldercherry.com", "oldercherry.com",
        "sexymilfpussy.com", "maturepornpics.com", "action36.com", "dianapost.com",
        "babesclub.net", "lovely-mature.net", "bestmaturesthumb.com",
        "myfreemoms.com", "milfatwork.net", "milfgals.net", "olderwomenarchive.com",
        "milfmomspics.com", "pornvideoitaly.com", "stiflersmilfs.com",
        "maturenags.com", "maturenakedsluts.com", "tgpmaturewoman.com",
        "idealwifes.com", "maturewitch.com", "hqmaturemovs.com",
        "mature-women-tube.org", "olderwomentaboo.com", "chocomilf.com",
        "milfparanoia.com", "momsnightjob.com", "matureintros.com", "booloo.com",
        "bigbuttmature.com", "maturetube.com", "mature30-45.com", "pornbox.org",
        "honestpornreviews.com", "crocreview.com", "realitypornsearch.com",
        "paypornlist.net", "rogreviews.com", "thetongue.net", "porninspector.com",
        "backroomfacials.com", "pawg.com", "nailedhard.com", "fuckteamfive.com",
        "bangbros18teens.com", "partyofthree.com", "latinarampage.com",
        "backroommilf.com", "canhescore.com", "mujeresculonas.net", "xkeezmovies.com",
        "bangpov.com", "bang.com", "porndoe.com", "blowjobninjas.com", "mrpornx.com",
        "mydirtymaid.net", "stepmomvideos.com", "rabbitsreviews.com", "empflix.com",
        "boobpedia.com", "dorminvasion.com", "easyporn.tv", "rexmag.com", "fux.com",
        "pornadept.com", "mylifeinbrazil.com", "yespornpleae.com", "ultrahorny.com",
        "momishorny.com", "bangoncasting.com", "bangbros-free.com", "720porn.net",
        "funvidporn.com", "bangpass.com", "siterip4fun.com", "bangbros.com",
        "porntube.com", "youjizz.com", "redtube.com", "xvideos.com", "xhamster.com",
        "xnxx.com", "youporn.com", "hclips.com", "porn.com", "tnaflix.com",
        "tube8.com", "hd21.com", "newhd.xxx", "spankbang.com", "drtuber.com",
        "spankwire.com", "keezmovies.com", "nuvid.com", "sunporno.com",
        "bravotube.net", "bravoteens.com", "drtuber.com", "mylust.com",
        "overthumbs.com", "palmtube.com", "pornhd.com", "porn300.com", "sexvid.xxx",
        "xxxbunker.com", "mofosex.com", "xbabe.com", "updatetube.com", "befuck.com",
        "bravoerotica.com", "masseurporn.com", "hdmovz.com", "pornrox.com",
        "pornmaki.com", "pornid.xxx", "inxporn.com", "slutload.com", "proporn.com",
        "fakeporn.tv", "pornhost.com", "handjobhub.com", "vpornvideos.com",
        "myxvids.com", "dansmovies.com", "fapdu.com", "rude.com",
        "topfreepornvideos.com", "freudbox.com", "pornheed.com", "hdporn.net",
        "orgasm.com", "pornrabbit.com", "madthumbs.com", "fux.com", "eroxia.com",
        "deviantclip.com", "xxvids.net", "h2porn.com", "apetube.com", "metaporn.com",
        "elephanttube.com", "long.xxx", "pornerbros.com", "iporntv.net", "pron.tv",
        "pornplanner.com", "mypornbible.com", "badjojo.com", "findtubes.com",
        "lasmejoreswebsporno.com/en", "pornmd.com", "nudevista.com",
        "it.bing.com/videos/search?q=por",
        "video.search.yahoo.com/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=ZaF57phvPYQ,138531013",
        "video.search.yahoo.com/search/video?fr=sfp&fr2=piv-web&p=porn&.bcrumb=t2freeITUJs,1526679329&fr2=p%3As%2Cv%3Av&save=0",
        "adultvideofinder.com", "awejmp.com", "imlive.com", "evilangellive.com",
        "awejmp.com", "joyourself.com", "xlovecam.com", "cams.com", "pornication.com",
        "delhisexchat.com", "sexier.com", "secure.vividcams.com", "privatefeeds.com",
        "streamate.com", "slutroulette.com", "t.hrtya.com", "watchmyexgf.net",
        "watchmygf.cc", "fantasti.cc", "watchmygf.me", "iknowthatgirl.com",
        "daredorm.com", "crazycollegegfs.com", "analized.com", "punishtube.com",
        "stufferdb.com", "88gals.com", "sexforums.com/gallery", "apina.biz",
        "babe-lounge.com", "fuskator.com", "gotporn.com", "arabianchicks.com",
        "extremetube.com", "fetishpapa.com", "fuckler.com", "fantasti.cc",
        "bdsmstreak.com", "zzcartoon.com", "animeidhentai.com", "hentaihaven.org",
        "simply-hentai.com", "hentaigasm.com", "fakku.net", "gelbooru.com",
        "hentaipulse.com", "porcore.com", "hentaischool.com",
        "chan.sankakucomplex.com", "hentai-foundry.com", "babesrater.com",
        "punchpin.com", "lustpin.com", "sexlikereal.com", "vrsmash.com", "stasyq.com",
        "mobilevrxxx.com", "realitylovers.com", "myporngay.com", "zzgays.com",
        "gay-lounge.net", "justusboys.com", "iptorrents.com/torrents", "rarbg.com",
        "pussytorrents.org", "porn.com", "yourdailypornstars.com",
        "bestpornstardb.com", "babepedia.com", "kindgirls.com", "playindiansex.com",
        "playindianporn.com", "viewdesisex.com", "hotsouthindiansex.com",
        "watchindianporn.net", "xpaja.net", "lesbian8.com", "kirtu.com",
        "velamma.com", "nutaku.net", "69games.xxx", "gamcore.com",
        "assist.lifeselector.com", "playforceone.com", "brazzersnetwork.com",
        "wct.link", "rk.com", "digitalplayground.com", "mofosnetwork.com",
        "gfrevenge.com", "twistysnetwork.com", "teamskeet.com", "bangbrosnetwork.com",
        "iyalc.com", "ddfnetwork.com", "braincash.com", "iyalc.com", "videosz.com",
        "hustler.com", "premiumbukkake.com", "javhd.com", "pornprosnetwork.com",
        "perfectgonzo.com", "alljapanesepass.com", "momsbangteens.com",
        "wickedpictures.com", "puffynetwork.com", "18videoz.com", "nubiles.net",
        "kinkyfamily.com", "allofgfs.com", "filf.com", "dorcelclub.com",
        "best-paypornsites.com", "nakednews.com", "playboy.com", "forumophilia.com",
        "jdforum.net", "freeones.com", "peachyforum.com", "sexyrealsexdolls.com",
        "spklmis.com", "toppornsites.com", "Tubegalore.com", "gaymaletube.com",
        "iXXX.com", "1piecehentai.com", "2hentai.com", "2th.com", "4chan.com",
        "69ani.com", "8muses.com", "aerisdies.com", "allhentai.com",
        "animefootfetish.com", "animehentaimangas.com", "animetor.com",
        "animephile.com", "aryion.com", "asmhentai.com", "atsuifeet.com", "baidu.com",
        "baixarhentai.com", "bamtoki.com", "bangcartoons.com", "baramangaonline.com",
        "bbotoon.com", "bobx.com", "brasilhentai.com", "clickhentai.com",
        "codegeassxxx.com", "colorhentaimangas.com", "comicsfromhell.com",
        "comicsporno.com", "comicspornogratis.com", "comixhere.com",
        "deliciousdoujinshi.com", "dochentai.com", "doujin2.com", "doujin-th.com",
        "doujindaily.com", "doujinland.com", "doujinlife.com",
        "doujinloverandgiver.com", "doujinmode.com", "doujinpage.com",
        "doujinreader.com", "doujinroom.com", "doujins.com", "doujinshentai.com",
        "doujinshi rocks.com", "doujinshihentai.com", "doujinx.com", "e-hentai.com",
        "ecchitail.com", "ero-senin.com", "erolord.com", "eromanga-sokuhou.com",
        "eshentaionline.com.com", "exhentai.com", "fapdu.com", "ff10hentai.com",
        "ff12hentai.com", "ff7hentai.com", "finalxxxfantasy.com", "furaffinity.com",
        "futahentai.com", "futanarispash.com", "g6hentai.com", "gs-uploader.com",
        "gurrenhentai.com", "h-manga moe.com", "hakihome.com", "hbrowse.com",
        "hcomicbook.com", "hdarkzone.com", "hellven.com", "hentai-ddl.com",
        "hentai-free.com", "hentai-id.com", "hentai-ita.com", "hentai-manga.com",
        "hentaicafe.com", "hentaims.com", "hentaipink.com", "hentaltl.com",
        "hental2read.com", "hentai4me.com", "hentai4doujin.com", "hentai4manga.com",
        "hentai4u.com", "hentai666.com", "hentaibeast.com", "hentaiboxfr.com",
        "hentaibox.com", "hentaibunny.com", "hentaibusty.com", "hentaichan.com",
        "hentaicloud.com", "hentaicorner.com", "hentaifamed.com", "hentaifield.com",
        "hentaifox.com", "hentaifr.com", "hentaifromhell.com", "hentaigamech.com",
        "hentaigratuit.com", "hentaihere.com", "hentaihouse.com", "hentaihousext.com",
        "hentaihunt.com", "hentaiiXXX.com", "hentaijuggs.com", "hentailx.com",
        "hentailxers.com", "hentaimangabiz.com", "hentaimangaonline.com",
        "hentaimangaz.com", "hentainesia.com", "hentaiporns.com", "hentairead.com",
        "henairing.com", "hentairules.com", "hentaischool.com", "hentaisd.com",
        "hentaistack.com", "hentaivn.com", "hentype.com", "hgamecg.com", "hhhhhh.com",
        "high-hentai.com", "hime-doujins.com", "hipercool.com", "hitomi.com",
        "hmangasearcher.com", "hotdhentai.com", "ihentaimanga.com", "imagefap.com",
        "incesthentai.com", "junkuchan.com", "kimi-h.com", "komikhentai.com",
        "lolhentai.com", "lookmanga.com", "lovehentaimanga.com", "luscious.com",
        "ohentai.com", "mahenku.com", "manga12.com", "mangaboxes.com", "mangafap.com",
        "mangakawaiifeet.com", "manganude.com", "mangaray.com", "mangaseries.com",
        "mangawindow.com", "mapussy.com", "massivehentai.com", "maturemangas.com",
        "megahentaicomics.com", "milkyhentai.com", "minihentai.com",
        "muchodoujins.com", "muchohentai.com", "multporn.com", "mydoujins.com",
        "myhentaicomics.com", "myreadingmanga.com", "narutohentaigalleries.com",
        "nhentai.com", "nude-moon.com", "nxt-comics.com", "ohtori.com",
        "omorashi.com", "overwatchhentaidb.com", "palcomix.com", "pbxwwoec.com",
        "personahentai.com", "perveden.com", "pinayacenter.com", "plentyofhentai.com",
        "pomfpomf.com", "porncomics.com", "porncmix.com", "pornocomics.com",
        "pornsource.com", "pornxxxcomics.com", "primehentai.com", "proxer.com",
        "pururin.com", "r34comics.com", "readhentaidoujinshi.com",
        "readhentaimanga.com", "readincesthentai.com", "readmangahentai.com",
        "revistasequadrinhos.com", "ryuutama.com", "sextgem.com", "shentai.com",
        "simply-hentai.com", "sinnergate.com", "smdc-translations.com",
        "sohentai.com", "submanga.com", "sukahentai.com", "svscomics.com",
        "sweetyaoiparadise.com", "thedoujin.com", "thehentaiworld.com",
        "tmohentai.com", "truyen18.com", "tsumino.com", "underworld-scans.com",
        "fapworks.com", "vanillahentai.com", "ver-manga.com", "vercomicsporno.com",
        "vesquare.com", "watchhentaistream.com", "world-hentai.com", "xcartx.com",
        "xcomics4you.com", "xxcomics.com", "xxxyuna.com", "yaoichan.com",
        "yaoifox.com", "yaoihavenreborn.com", "yuri-ism.com", "yurimanga.com",
        "zizki.com", "zkomik.com", "findtubes.com", "1indiansex.net", "3rat.com",
        "4hen.com", "africansexvideos.net", "bananabunny.com", "cutepornvideos.com",
        "desimurga.com", "desisexclips.com", "dslady.com", "eroticperfection.com",
        "porn.com", "porn.org", "gaypormium.com", "gracefulnudes.com",
        "hot-dates.info", "hqlinks.net", "indiansex4u.com.xxx", "jav-porn.net",
        "legalporno.com", "luboeporno.com", "pinkythekinky.com", "sexsex.hu",
        "sexxxi.com", "semale.asia", "thefreecamsecret.com", "momsteachsex.com",
        "petardas.com", "89.com", "alohatube.com", "babosas.com", "callboyindia.com",
        "cam4.co", "cam4.com", "cam4.in", "cholotube.com", "cliphunter.com",
        "culosgratis.com", "cumlouder.com", "darering.com", "flirt4free.com",
        "fuq.com", "hairy.com", "labatidora.net", "leche69.com", "livejasmin.com",
        "locasporfollar.com", "lushstories.com", "mc-nudes.com", "myfreecams.com",
        "naughty.com", "penguinvids.com", "perfectgirls.com", "perucaseras.com",
        "pinkworld.com", "playvid.com", "puritanas.com", "rk.com",
        "roundandbrown.com", "truthordarepics.com", "videosdemadurasx.com",
        "x-ho.com", "xixx.com", "xtube.com", "xvideosnacional.com", "purebbwtube.com",
        "babes.com", "fotosmujeres.pibones.com", "rubber-kingdom.com",
        "savitabhabhi.mobi", "pinkvisualtgp.com", "antarvasna.com", "hot-gifz.com",
        "lechecaliente.com", "parejasfollando.es", "flirthookup.com", "cerdas.com",
        "chaturbate.com", "ledauphine.com", "freex.mobi", "gokabyle.com",
        "bdenjoymore.blogspot.com", "petardas.com", "conejox.com", "voyeurpipi.com",
        "gouines.pornoxxxi.net", "arabebaise.com", "ohasiatique.com", "poringa.net",
        "lisaannlovers11.tumblr.com", "h33t.to", "marocainenue.com",
        "gorgeousladies.com", "fille-nue-video.com", "teensnow.com",
        "theofficiallouisejenson.co", "yourather.com", "bootlust.com",
        "toonztube.com", "top-chatroulette.com", "videosfilleschaudes.com",
        "fillechaude.org", "femmesmuresx.net", "liberteenage.com", "coffeetube.com",
        "awesomeellalove.tumblr.com", "xnxxgifs.com", "saoulbadjojo.com",
        "beurettehot.net", "woodstockreborn.tumblr.com",
        "belles-femmes-arabes.blogspot.com", "xgouines.com", "couleurlvoirce.com",
        "3animalsextube.com", "moncloutube.net", "sexocean.com", "femdomempire.com",
        "babosas.co", "giude-asie.com", "beauxcul.com", "maghrebinnes.xl.cx",
        "xnxx-free.net", "xnxx.vc", "es.bravotube.net", "rubias19.com",
        "xxl.onxille.com", "asiataique-femme.com", "masalopeblack.com",
        "beautiful-nude-tens-exposed.tur", "pormhub.com", "cochonnevideosx.com", "videosanalesx.com",
        "dorceltv.xn.pl", "salope-marocaine.com", "jeunette18.com", "redtuve.com",
        "les-grosses.net", "yasminramos.com", "tukif.com", "adultwork.com",
        "hairy.com", "tendance-lesbienne.com", "indiansexstories.net", "eros.com",
        "7dog.com", "vivthomas.com", "teensnowxvideos.com",
        "x-art.com","chaturbate.com","pinkworld.com","pandamovies.com","muyzorras.com","uplust.com",
        "shemales.com","bigboobsalert.com","culx.org","falconstudios.com","nautilix.com","ovideox.com",
        "herbalviagraworld.com","primecurves.com","xbabe.com","webpnudes.com",
        "smutty.com","naughtyamerica.com","faketaxi.com","momjoi.com","dreammovies.com", "swallowed.com",
        "asspoint.com", "bobs-tube.com", "4tube.com", "canalporno.com", "eporner.com",
        "hdpornt.com", "kink.com", "milffox.com", "mypornstarbook.com", "xshare.com"
    };

//    static Map<String, Boolean> dict = new HashMap<String, Boolean>();
//
//
//    public static void init() {
//        for (int i = 0; i < pornLinks.length; i++) {
//            dict.put(pornLinks[i],true);
//        }
//    }

}
